// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_wrapper_ap_ufixed_4_0_4_0_0_ap_fixed_14_7_5_3_0_config11_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        data_20_V_read,
        data_21_V_read,
        data_22_V_read,
        data_23_V_read,
        data_24_V_read,
        data_25_V_read,
        data_26_V_read,
        data_27_V_read,
        data_28_V_read,
        data_29_V_read,
        data_30_V_read,
        data_31_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] data_0_V_read;
input  [3:0] data_1_V_read;
input  [3:0] data_2_V_read;
input  [3:0] data_3_V_read;
input  [3:0] data_4_V_read;
input  [3:0] data_5_V_read;
input  [3:0] data_6_V_read;
input  [3:0] data_7_V_read;
input  [3:0] data_8_V_read;
input  [3:0] data_9_V_read;
input  [3:0] data_10_V_read;
input  [3:0] data_11_V_read;
input  [3:0] data_12_V_read;
input  [3:0] data_13_V_read;
input  [3:0] data_14_V_read;
input  [3:0] data_15_V_read;
input  [3:0] data_16_V_read;
input  [3:0] data_17_V_read;
input  [3:0] data_18_V_read;
input  [3:0] data_19_V_read;
input  [3:0] data_20_V_read;
input  [3:0] data_21_V_read;
input  [3:0] data_22_V_read;
input  [3:0] data_23_V_read;
input  [3:0] data_24_V_read;
input  [3:0] data_25_V_read;
input  [3:0] data_26_V_read;
input  [3:0] data_27_V_read;
input  [3:0] data_28_V_read;
input  [3:0] data_29_V_read;
input  [3:0] data_30_V_read;
input  [3:0] data_31_V_read;
output  [13:0] ap_return_0;
output  [13:0] ap_return_1;
output  [13:0] ap_return_2;
output  [13:0] ap_return_3;
output  [13:0] ap_return_4;
output  [13:0] ap_return_5;
output  [13:0] ap_return_6;
output  [13:0] ap_return_7;
output  [13:0] ap_return_8;
output  [13:0] ap_return_9;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[13:0] ap_return_0;
reg[13:0] ap_return_1;
reg[13:0] ap_return_2;
reg[13:0] ap_return_3;
reg[13:0] ap_return_4;
reg[13:0] ap_return_5;
reg[13:0] ap_return_6;
reg[13:0] ap_return_7;
reg[13:0] ap_return_8;
reg[13:0] ap_return_9;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln135_fu_1453_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] outidx_address0;
reg    outidx_ce0;
wire   [0:0] outidx_q0;
wire   [5:0] w11_V_address0;
reg    w11_V_ce0;
wire   [19:0] w11_V_q0;
reg   [0:0] do_init_reg_370;
reg   [3:0] data_0_V_read39_rewind_reg_386;
reg   [3:0] data_1_V_read40_rewind_reg_400;
reg   [3:0] data_2_V_read41_rewind_reg_414;
reg   [3:0] data_3_V_read42_rewind_reg_428;
reg   [3:0] data_4_V_read43_rewind_reg_442;
reg   [3:0] data_5_V_read44_rewind_reg_456;
reg   [3:0] data_6_V_read45_rewind_reg_470;
reg   [3:0] data_7_V_read46_rewind_reg_484;
reg   [3:0] data_8_V_read47_rewind_reg_498;
reg   [3:0] data_9_V_read48_rewind_reg_512;
reg   [3:0] data_10_V_read49_rewind_reg_526;
reg   [3:0] data_11_V_read50_rewind_reg_540;
reg   [3:0] data_12_V_read51_rewind_reg_554;
reg   [3:0] data_13_V_read52_rewind_reg_568;
reg   [3:0] data_14_V_read53_rewind_reg_582;
reg   [3:0] data_15_V_read54_rewind_reg_596;
reg   [3:0] data_16_V_read55_rewind_reg_610;
reg   [3:0] data_17_V_read56_rewind_reg_624;
reg   [3:0] data_18_V_read57_rewind_reg_638;
reg   [3:0] data_19_V_read58_rewind_reg_652;
reg   [3:0] data_20_V_read59_rewind_reg_666;
reg   [3:0] data_21_V_read60_rewind_reg_680;
reg   [3:0] data_22_V_read61_rewind_reg_694;
reg   [3:0] data_23_V_read62_rewind_reg_708;
reg   [3:0] data_24_V_read63_rewind_reg_722;
reg   [3:0] data_25_V_read64_rewind_reg_736;
reg   [3:0] data_26_V_read65_rewind_reg_750;
reg   [3:0] data_27_V_read66_rewind_reg_764;
reg   [3:0] data_28_V_read67_rewind_reg_778;
reg   [3:0] data_29_V_read68_rewind_reg_792;
reg   [3:0] data_30_V_read69_rewind_reg_806;
reg   [3:0] data_31_V_read70_rewind_reg_820;
reg   [5:0] w_index38_reg_834;
reg   [31:0] in_index_0_i37_reg_848;
reg   [3:0] data_0_V_read39_phi_reg_863;
reg   [3:0] data_1_V_read40_phi_reg_876;
reg   [3:0] data_2_V_read41_phi_reg_889;
reg   [3:0] data_3_V_read42_phi_reg_902;
reg   [3:0] data_4_V_read43_phi_reg_915;
reg   [3:0] data_5_V_read44_phi_reg_928;
reg   [3:0] data_6_V_read45_phi_reg_941;
reg   [3:0] data_7_V_read46_phi_reg_954;
reg   [3:0] data_8_V_read47_phi_reg_967;
reg   [3:0] data_9_V_read48_phi_reg_980;
reg   [3:0] data_10_V_read49_phi_reg_993;
reg   [3:0] data_11_V_read50_phi_reg_1006;
reg   [3:0] data_12_V_read51_phi_reg_1019;
reg   [3:0] data_13_V_read52_phi_reg_1032;
reg   [3:0] data_14_V_read53_phi_reg_1045;
reg   [3:0] data_15_V_read54_phi_reg_1058;
reg   [3:0] data_16_V_read55_phi_reg_1071;
reg   [3:0] data_17_V_read56_phi_reg_1084;
reg   [3:0] data_18_V_read57_phi_reg_1097;
reg   [3:0] data_19_V_read58_phi_reg_1110;
reg   [3:0] data_20_V_read59_phi_reg_1123;
reg   [3:0] data_21_V_read60_phi_reg_1136;
reg   [3:0] data_22_V_read61_phi_reg_1149;
reg   [3:0] data_23_V_read62_phi_reg_1162;
reg   [3:0] data_24_V_read63_phi_reg_1175;
reg   [3:0] data_25_V_read64_phi_reg_1188;
reg   [3:0] data_26_V_read65_phi_reg_1201;
reg   [3:0] data_27_V_read66_phi_reg_1214;
reg   [3:0] data_28_V_read67_phi_reg_1227;
reg   [3:0] data_29_V_read68_phi_reg_1240;
reg   [3:0] data_30_V_read69_phi_reg_1253;
reg   [3:0] data_31_V_read70_phi_reg_1266;
reg   [13:0] res_9_V_write_assign36_reg_1279;
reg   [13:0] res_8_V_write_assign34_reg_1293;
reg   [13:0] res_7_V_write_assign32_reg_1307;
reg   [13:0] res_6_V_write_assign30_reg_1321;
reg   [13:0] res_5_V_write_assign28_reg_1335;
reg   [13:0] res_4_V_write_assign26_reg_1349;
reg   [13:0] res_3_V_write_assign24_reg_1363;
reg   [13:0] res_2_V_write_assign22_reg_1377;
reg   [13:0] res_1_V_write_assign20_reg_1391;
reg   [13:0] res_0_V_write_assign18_reg_1405;
wire   [31:0] in_index_fu_1425_p2;
reg   [31:0] in_index_reg_1826;
wire   [0:0] icmp_ln154_fu_1441_p2;
reg   [0:0] icmp_ln154_reg_1831;
wire   [5:0] w_index_fu_1447_p2;
reg   [5:0] w_index_reg_1836;
reg   [0:0] icmp_ln135_reg_1841;
reg   [0:0] icmp_ln135_reg_1841_pp0_iter1_reg;
reg   [0:0] icmp_ln135_reg_1841_pp0_iter2_reg;
reg   [0:0] out_index_reg_1845;
reg   [0:0] out_index_reg_1845_pp0_iter2_reg;
wire   [7:0] zext_ln1116_fu_1537_p1;
wire   [31:0] select_ln154_fu_1601_p3;
reg    ap_enable_reg_pp0_iter1;
wire   [13:0] acc_1_V_1_fu_1614_p3;
reg    ap_enable_reg_pp0_iter3;
wire   [13:0] acc_1_V_2_fu_1620_p3;
wire   [13:0] acc_3_V_1_fu_1633_p3;
wire   [13:0] acc_3_V_2_fu_1639_p3;
wire   [13:0] acc_5_V_1_fu_1652_p3;
wire   [13:0] acc_5_V_2_fu_1658_p3;
wire   [13:0] acc_7_V_1_fu_1671_p3;
wire   [13:0] acc_7_V_2_fu_1677_p3;
wire   [13:0] acc_9_V_1_fu_1690_p3;
wire   [13:0] acc_9_V_2_fu_1696_p3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] ap_phi_mux_do_init_phi_fu_374_p6;
wire    ap_block_pp0_stage0;
reg   [3:0] ap_phi_mux_data_0_V_read39_rewind_phi_fu_390_p6;
reg   [3:0] ap_phi_mux_data_1_V_read40_rewind_phi_fu_404_p6;
reg   [3:0] ap_phi_mux_data_2_V_read41_rewind_phi_fu_418_p6;
reg   [3:0] ap_phi_mux_data_3_V_read42_rewind_phi_fu_432_p6;
reg   [3:0] ap_phi_mux_data_4_V_read43_rewind_phi_fu_446_p6;
reg   [3:0] ap_phi_mux_data_5_V_read44_rewind_phi_fu_460_p6;
reg   [3:0] ap_phi_mux_data_6_V_read45_rewind_phi_fu_474_p6;
reg   [3:0] ap_phi_mux_data_7_V_read46_rewind_phi_fu_488_p6;
reg   [3:0] ap_phi_mux_data_8_V_read47_rewind_phi_fu_502_p6;
reg   [3:0] ap_phi_mux_data_9_V_read48_rewind_phi_fu_516_p6;
reg   [3:0] ap_phi_mux_data_10_V_read49_rewind_phi_fu_530_p6;
reg   [3:0] ap_phi_mux_data_11_V_read50_rewind_phi_fu_544_p6;
reg   [3:0] ap_phi_mux_data_12_V_read51_rewind_phi_fu_558_p6;
reg   [3:0] ap_phi_mux_data_13_V_read52_rewind_phi_fu_572_p6;
reg   [3:0] ap_phi_mux_data_14_V_read53_rewind_phi_fu_586_p6;
reg   [3:0] ap_phi_mux_data_15_V_read54_rewind_phi_fu_600_p6;
reg   [3:0] ap_phi_mux_data_16_V_read55_rewind_phi_fu_614_p6;
reg   [3:0] ap_phi_mux_data_17_V_read56_rewind_phi_fu_628_p6;
reg   [3:0] ap_phi_mux_data_18_V_read57_rewind_phi_fu_642_p6;
reg   [3:0] ap_phi_mux_data_19_V_read58_rewind_phi_fu_656_p6;
reg   [3:0] ap_phi_mux_data_20_V_read59_rewind_phi_fu_670_p6;
reg   [3:0] ap_phi_mux_data_21_V_read60_rewind_phi_fu_684_p6;
reg   [3:0] ap_phi_mux_data_22_V_read61_rewind_phi_fu_698_p6;
reg   [3:0] ap_phi_mux_data_23_V_read62_rewind_phi_fu_712_p6;
reg   [3:0] ap_phi_mux_data_24_V_read63_rewind_phi_fu_726_p6;
reg   [3:0] ap_phi_mux_data_25_V_read64_rewind_phi_fu_740_p6;
reg   [3:0] ap_phi_mux_data_26_V_read65_rewind_phi_fu_754_p6;
reg   [3:0] ap_phi_mux_data_27_V_read66_rewind_phi_fu_768_p6;
reg   [3:0] ap_phi_mux_data_28_V_read67_rewind_phi_fu_782_p6;
reg   [3:0] ap_phi_mux_data_29_V_read68_rewind_phi_fu_796_p6;
reg   [3:0] ap_phi_mux_data_30_V_read69_rewind_phi_fu_810_p6;
reg   [3:0] ap_phi_mux_data_31_V_read70_rewind_phi_fu_824_p6;
reg   [5:0] ap_phi_mux_w_index38_phi_fu_838_p6;
reg   [31:0] ap_phi_mux_in_index_0_i37_phi_fu_852_p6;
wire   [3:0] ap_phi_reg_pp0_iter0_data_0_V_read39_phi_reg_863;
wire   [3:0] ap_phi_reg_pp0_iter0_data_1_V_read40_phi_reg_876;
wire   [3:0] ap_phi_reg_pp0_iter0_data_2_V_read41_phi_reg_889;
wire   [3:0] ap_phi_reg_pp0_iter0_data_3_V_read42_phi_reg_902;
wire   [3:0] ap_phi_reg_pp0_iter0_data_4_V_read43_phi_reg_915;
wire   [3:0] ap_phi_reg_pp0_iter0_data_5_V_read44_phi_reg_928;
wire   [3:0] ap_phi_reg_pp0_iter0_data_6_V_read45_phi_reg_941;
wire   [3:0] ap_phi_reg_pp0_iter0_data_7_V_read46_phi_reg_954;
wire   [3:0] ap_phi_reg_pp0_iter0_data_8_V_read47_phi_reg_967;
wire   [3:0] ap_phi_reg_pp0_iter0_data_9_V_read48_phi_reg_980;
wire   [3:0] ap_phi_reg_pp0_iter0_data_10_V_read49_phi_reg_993;
wire   [3:0] ap_phi_reg_pp0_iter0_data_11_V_read50_phi_reg_1006;
wire   [3:0] ap_phi_reg_pp0_iter0_data_12_V_read51_phi_reg_1019;
wire   [3:0] ap_phi_reg_pp0_iter0_data_13_V_read52_phi_reg_1032;
wire   [3:0] ap_phi_reg_pp0_iter0_data_14_V_read53_phi_reg_1045;
wire   [3:0] ap_phi_reg_pp0_iter0_data_15_V_read54_phi_reg_1058;
wire   [3:0] ap_phi_reg_pp0_iter0_data_16_V_read55_phi_reg_1071;
wire   [3:0] ap_phi_reg_pp0_iter0_data_17_V_read56_phi_reg_1084;
wire   [3:0] ap_phi_reg_pp0_iter0_data_18_V_read57_phi_reg_1097;
wire   [3:0] ap_phi_reg_pp0_iter0_data_19_V_read58_phi_reg_1110;
wire   [3:0] ap_phi_reg_pp0_iter0_data_20_V_read59_phi_reg_1123;
wire   [3:0] ap_phi_reg_pp0_iter0_data_21_V_read60_phi_reg_1136;
wire   [3:0] ap_phi_reg_pp0_iter0_data_22_V_read61_phi_reg_1149;
wire   [3:0] ap_phi_reg_pp0_iter0_data_23_V_read62_phi_reg_1162;
wire   [3:0] ap_phi_reg_pp0_iter0_data_24_V_read63_phi_reg_1175;
wire   [3:0] ap_phi_reg_pp0_iter0_data_25_V_read64_phi_reg_1188;
wire   [3:0] ap_phi_reg_pp0_iter0_data_26_V_read65_phi_reg_1201;
wire   [3:0] ap_phi_reg_pp0_iter0_data_27_V_read66_phi_reg_1214;
wire   [3:0] ap_phi_reg_pp0_iter0_data_28_V_read67_phi_reg_1227;
wire   [3:0] ap_phi_reg_pp0_iter0_data_29_V_read68_phi_reg_1240;
wire   [3:0] ap_phi_reg_pp0_iter0_data_30_V_read69_phi_reg_1253;
wire   [3:0] ap_phi_reg_pp0_iter0_data_31_V_read70_phi_reg_1266;
wire   [63:0] zext_ln139_fu_1419_p1;
wire   [26:0] tmp_430_fu_1431_p4;
wire   [4:0] tmp_523_fu_1463_p33;
wire   [3:0] tmp_523_fu_1463_p34;
wire  signed [3:0] trunc_ln145_1_fu_1533_p1;
wire  signed [3:0] tmp_524_fu_1545_p4;
wire  signed [3:0] tmp_525_fu_1559_p4;
wire  signed [3:0] tmp_526_fu_1573_p4;
wire  signed [3:0] tmp_527_fu_1587_p4;
wire  signed [13:0] grp_fu_1766_p3;
wire  signed [13:0] grp_fu_1776_p3;
wire  signed [13:0] grp_fu_1786_p3;
wire  signed [13:0] grp_fu_1796_p3;
wire  signed [13:0] grp_fu_1806_p3;
wire   [3:0] grp_fu_1766_p0;
wire   [13:0] grp_fu_1766_p2;
wire   [3:0] grp_fu_1776_p0;
wire   [13:0] grp_fu_1776_p2;
wire   [3:0] grp_fu_1786_p0;
wire   [13:0] grp_fu_1786_p2;
wire   [3:0] grp_fu_1796_p0;
wire   [13:0] grp_fu_1796_p2;
wire   [3:0] grp_fu_1806_p0;
wire   [13:0] grp_fu_1806_p2;
reg    grp_fu_1766_ce;
reg    grp_fu_1776_ce;
reg    grp_fu_1786_ce;
reg    grp_fu_1796_ce;
reg    grp_fu_1806_ce;
reg   [13:0] ap_return_0_preg;
reg   [13:0] ap_return_1_preg;
reg   [13:0] ap_return_2_preg;
reg   [13:0] ap_return_3_preg;
reg   [13:0] ap_return_4_preg;
reg   [13:0] ap_return_5_preg;
reg   [13:0] ap_return_6_preg;
reg   [13:0] ap_return_7_preg;
reg   [13:0] ap_return_8_preg;
reg   [13:0] ap_return_9_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_329;
reg    ap_condition_41;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_return_0_preg = 14'd0;
#0 ap_return_1_preg = 14'd0;
#0 ap_return_2_preg = 14'd0;
#0 ap_return_3_preg = 14'd0;
#0 ap_return_4_preg = 14'd0;
#0 ap_return_5_preg = 14'd0;
#0 ap_return_6_preg = 14'd0;
#0 ap_return_7_preg = 14'd0;
#0 ap_return_8_preg = 14'd0;
#0 ap_return_9_preg = 14'd0;
end

dense_wrapper_ap_ufixed_4_0_4_0_0_ap_fixed_14_7_5_3_0_config11_s_outidx #(
    .DataWidth( 1 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
outidx_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx_address0),
    .ce0(outidx_ce0),
    .q0(outidx_q0)
);

dense_wrapper_ap_ufixed_4_0_4_0_0_ap_fixed_14_7_5_3_0_config11_s_w11_V #(
    .DataWidth( 20 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
w11_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w11_V_address0),
    .ce0(w11_V_ce0),
    .q0(w11_V_q0)
);

myproject_axi_mux_325_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .din3_WIDTH( 4 ),
    .din4_WIDTH( 4 ),
    .din5_WIDTH( 4 ),
    .din6_WIDTH( 4 ),
    .din7_WIDTH( 4 ),
    .din8_WIDTH( 4 ),
    .din9_WIDTH( 4 ),
    .din10_WIDTH( 4 ),
    .din11_WIDTH( 4 ),
    .din12_WIDTH( 4 ),
    .din13_WIDTH( 4 ),
    .din14_WIDTH( 4 ),
    .din15_WIDTH( 4 ),
    .din16_WIDTH( 4 ),
    .din17_WIDTH( 4 ),
    .din18_WIDTH( 4 ),
    .din19_WIDTH( 4 ),
    .din20_WIDTH( 4 ),
    .din21_WIDTH( 4 ),
    .din22_WIDTH( 4 ),
    .din23_WIDTH( 4 ),
    .din24_WIDTH( 4 ),
    .din25_WIDTH( 4 ),
    .din26_WIDTH( 4 ),
    .din27_WIDTH( 4 ),
    .din28_WIDTH( 4 ),
    .din29_WIDTH( 4 ),
    .din30_WIDTH( 4 ),
    .din31_WIDTH( 4 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 4 ))
myproject_axi_mux_325_4_1_1_U2325(
    .din0(data_0_V_read39_phi_reg_863),
    .din1(data_1_V_read40_phi_reg_876),
    .din2(data_2_V_read41_phi_reg_889),
    .din3(data_3_V_read42_phi_reg_902),
    .din4(data_4_V_read43_phi_reg_915),
    .din5(data_5_V_read44_phi_reg_928),
    .din6(data_6_V_read45_phi_reg_941),
    .din7(data_7_V_read46_phi_reg_954),
    .din8(data_8_V_read47_phi_reg_967),
    .din9(data_9_V_read48_phi_reg_980),
    .din10(data_10_V_read49_phi_reg_993),
    .din11(data_11_V_read50_phi_reg_1006),
    .din12(data_12_V_read51_phi_reg_1019),
    .din13(data_13_V_read52_phi_reg_1032),
    .din14(data_14_V_read53_phi_reg_1045),
    .din15(data_15_V_read54_phi_reg_1058),
    .din16(data_16_V_read55_phi_reg_1071),
    .din17(data_17_V_read56_phi_reg_1084),
    .din18(data_18_V_read57_phi_reg_1097),
    .din19(data_19_V_read58_phi_reg_1110),
    .din20(data_20_V_read59_phi_reg_1123),
    .din21(data_21_V_read60_phi_reg_1136),
    .din22(data_22_V_read61_phi_reg_1149),
    .din23(data_23_V_read62_phi_reg_1162),
    .din24(data_24_V_read63_phi_reg_1175),
    .din25(data_25_V_read64_phi_reg_1188),
    .din26(data_26_V_read65_phi_reg_1201),
    .din27(data_27_V_read66_phi_reg_1214),
    .din28(data_28_V_read67_phi_reg_1227),
    .din29(data_29_V_read68_phi_reg_1240),
    .din30(data_30_V_read69_phi_reg_1253),
    .din31(data_31_V_read70_phi_reg_1266),
    .din32(tmp_523_fu_1463_p33),
    .dout(tmp_523_fu_1463_p34)
);

myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1_U2326(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1766_p0),
    .din1(trunc_ln145_1_fu_1533_p1),
    .din2(grp_fu_1766_p2),
    .ce(grp_fu_1766_ce),
    .dout(grp_fu_1766_p3)
);

myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1_U2327(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1776_p0),
    .din1(tmp_524_fu_1545_p4),
    .din2(grp_fu_1776_p2),
    .ce(grp_fu_1776_ce),
    .dout(grp_fu_1776_p3)
);

myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1_U2328(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1786_p0),
    .din1(tmp_525_fu_1559_p4),
    .din2(grp_fu_1786_p2),
    .ce(grp_fu_1786_ce),
    .dout(grp_fu_1786_p3)
);

myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1_U2329(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1796_p0),
    .din1(tmp_526_fu_1573_p4),
    .din2(grp_fu_1796_p2),
    .ce(grp_fu_1796_ce),
    .dout(grp_fu_1796_p3)
);

myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1_U2330(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1806_p0),
    .din1(tmp_527_fu_1587_p4),
    .din2(grp_fu_1806_p2),
    .ce(grp_fu_1806_ce),
    .dout(grp_fu_1806_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_0_preg <= acc_1_V_1_fu_1614_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_1_preg <= acc_1_V_2_fu_1620_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_2_preg <= acc_3_V_1_fu_1633_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_3_preg <= acc_3_V_2_fu_1639_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_4_preg <= acc_5_V_1_fu_1652_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_5_preg <= acc_5_V_2_fu_1658_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_6_preg <= acc_7_V_1_fu_1671_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_7_preg <= acc_7_V_2_fu_1677_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_8_preg <= acc_9_V_1_fu_1690_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_9_preg <= acc_9_V_2_fu_1696_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_0_V_read39_phi_reg_863 <= ap_phi_mux_data_0_V_read39_rewind_phi_fu_390_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_0_V_read39_phi_reg_863 <= data_0_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_0_V_read39_phi_reg_863 <= ap_phi_reg_pp0_iter0_data_0_V_read39_phi_reg_863;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_10_V_read49_phi_reg_993 <= ap_phi_mux_data_10_V_read49_rewind_phi_fu_530_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_10_V_read49_phi_reg_993 <= data_10_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_10_V_read49_phi_reg_993 <= ap_phi_reg_pp0_iter0_data_10_V_read49_phi_reg_993;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_11_V_read50_phi_reg_1006 <= ap_phi_mux_data_11_V_read50_rewind_phi_fu_544_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_11_V_read50_phi_reg_1006 <= data_11_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_11_V_read50_phi_reg_1006 <= ap_phi_reg_pp0_iter0_data_11_V_read50_phi_reg_1006;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_12_V_read51_phi_reg_1019 <= ap_phi_mux_data_12_V_read51_rewind_phi_fu_558_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_12_V_read51_phi_reg_1019 <= data_12_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_12_V_read51_phi_reg_1019 <= ap_phi_reg_pp0_iter0_data_12_V_read51_phi_reg_1019;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_13_V_read52_phi_reg_1032 <= ap_phi_mux_data_13_V_read52_rewind_phi_fu_572_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_13_V_read52_phi_reg_1032 <= data_13_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_13_V_read52_phi_reg_1032 <= ap_phi_reg_pp0_iter0_data_13_V_read52_phi_reg_1032;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_14_V_read53_phi_reg_1045 <= ap_phi_mux_data_14_V_read53_rewind_phi_fu_586_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_14_V_read53_phi_reg_1045 <= data_14_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_14_V_read53_phi_reg_1045 <= ap_phi_reg_pp0_iter0_data_14_V_read53_phi_reg_1045;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_15_V_read54_phi_reg_1058 <= ap_phi_mux_data_15_V_read54_rewind_phi_fu_600_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_15_V_read54_phi_reg_1058 <= data_15_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_15_V_read54_phi_reg_1058 <= ap_phi_reg_pp0_iter0_data_15_V_read54_phi_reg_1058;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_16_V_read55_phi_reg_1071 <= ap_phi_mux_data_16_V_read55_rewind_phi_fu_614_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_16_V_read55_phi_reg_1071 <= data_16_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_16_V_read55_phi_reg_1071 <= ap_phi_reg_pp0_iter0_data_16_V_read55_phi_reg_1071;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_17_V_read56_phi_reg_1084 <= ap_phi_mux_data_17_V_read56_rewind_phi_fu_628_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_17_V_read56_phi_reg_1084 <= data_17_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_17_V_read56_phi_reg_1084 <= ap_phi_reg_pp0_iter0_data_17_V_read56_phi_reg_1084;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_18_V_read57_phi_reg_1097 <= ap_phi_mux_data_18_V_read57_rewind_phi_fu_642_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_18_V_read57_phi_reg_1097 <= data_18_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_18_V_read57_phi_reg_1097 <= ap_phi_reg_pp0_iter0_data_18_V_read57_phi_reg_1097;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_19_V_read58_phi_reg_1110 <= ap_phi_mux_data_19_V_read58_rewind_phi_fu_656_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_19_V_read58_phi_reg_1110 <= data_19_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_19_V_read58_phi_reg_1110 <= ap_phi_reg_pp0_iter0_data_19_V_read58_phi_reg_1110;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_1_V_read40_phi_reg_876 <= ap_phi_mux_data_1_V_read40_rewind_phi_fu_404_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_1_V_read40_phi_reg_876 <= data_1_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_1_V_read40_phi_reg_876 <= ap_phi_reg_pp0_iter0_data_1_V_read40_phi_reg_876;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_20_V_read59_phi_reg_1123 <= ap_phi_mux_data_20_V_read59_rewind_phi_fu_670_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_20_V_read59_phi_reg_1123 <= data_20_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_20_V_read59_phi_reg_1123 <= ap_phi_reg_pp0_iter0_data_20_V_read59_phi_reg_1123;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_21_V_read60_phi_reg_1136 <= ap_phi_mux_data_21_V_read60_rewind_phi_fu_684_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_21_V_read60_phi_reg_1136 <= data_21_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_21_V_read60_phi_reg_1136 <= ap_phi_reg_pp0_iter0_data_21_V_read60_phi_reg_1136;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_22_V_read61_phi_reg_1149 <= ap_phi_mux_data_22_V_read61_rewind_phi_fu_698_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_22_V_read61_phi_reg_1149 <= data_22_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_22_V_read61_phi_reg_1149 <= ap_phi_reg_pp0_iter0_data_22_V_read61_phi_reg_1149;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_23_V_read62_phi_reg_1162 <= ap_phi_mux_data_23_V_read62_rewind_phi_fu_712_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_23_V_read62_phi_reg_1162 <= data_23_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_23_V_read62_phi_reg_1162 <= ap_phi_reg_pp0_iter0_data_23_V_read62_phi_reg_1162;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_24_V_read63_phi_reg_1175 <= ap_phi_mux_data_24_V_read63_rewind_phi_fu_726_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_24_V_read63_phi_reg_1175 <= data_24_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_24_V_read63_phi_reg_1175 <= ap_phi_reg_pp0_iter0_data_24_V_read63_phi_reg_1175;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_25_V_read64_phi_reg_1188 <= ap_phi_mux_data_25_V_read64_rewind_phi_fu_740_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_25_V_read64_phi_reg_1188 <= data_25_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_25_V_read64_phi_reg_1188 <= ap_phi_reg_pp0_iter0_data_25_V_read64_phi_reg_1188;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_26_V_read65_phi_reg_1201 <= ap_phi_mux_data_26_V_read65_rewind_phi_fu_754_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_26_V_read65_phi_reg_1201 <= data_26_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_26_V_read65_phi_reg_1201 <= ap_phi_reg_pp0_iter0_data_26_V_read65_phi_reg_1201;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_27_V_read66_phi_reg_1214 <= ap_phi_mux_data_27_V_read66_rewind_phi_fu_768_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_27_V_read66_phi_reg_1214 <= data_27_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_27_V_read66_phi_reg_1214 <= ap_phi_reg_pp0_iter0_data_27_V_read66_phi_reg_1214;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_28_V_read67_phi_reg_1227 <= ap_phi_mux_data_28_V_read67_rewind_phi_fu_782_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_28_V_read67_phi_reg_1227 <= data_28_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_28_V_read67_phi_reg_1227 <= ap_phi_reg_pp0_iter0_data_28_V_read67_phi_reg_1227;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_29_V_read68_phi_reg_1240 <= ap_phi_mux_data_29_V_read68_rewind_phi_fu_796_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_29_V_read68_phi_reg_1240 <= data_29_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_29_V_read68_phi_reg_1240 <= ap_phi_reg_pp0_iter0_data_29_V_read68_phi_reg_1240;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_2_V_read41_phi_reg_889 <= ap_phi_mux_data_2_V_read41_rewind_phi_fu_418_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_2_V_read41_phi_reg_889 <= data_2_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_2_V_read41_phi_reg_889 <= ap_phi_reg_pp0_iter0_data_2_V_read41_phi_reg_889;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_30_V_read69_phi_reg_1253 <= ap_phi_mux_data_30_V_read69_rewind_phi_fu_810_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_30_V_read69_phi_reg_1253 <= data_30_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_30_V_read69_phi_reg_1253 <= ap_phi_reg_pp0_iter0_data_30_V_read69_phi_reg_1253;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_31_V_read70_phi_reg_1266 <= ap_phi_mux_data_31_V_read70_rewind_phi_fu_824_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_31_V_read70_phi_reg_1266 <= data_31_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_31_V_read70_phi_reg_1266 <= ap_phi_reg_pp0_iter0_data_31_V_read70_phi_reg_1266;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_3_V_read42_phi_reg_902 <= ap_phi_mux_data_3_V_read42_rewind_phi_fu_432_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_3_V_read42_phi_reg_902 <= data_3_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_3_V_read42_phi_reg_902 <= ap_phi_reg_pp0_iter0_data_3_V_read42_phi_reg_902;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_4_V_read43_phi_reg_915 <= ap_phi_mux_data_4_V_read43_rewind_phi_fu_446_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_4_V_read43_phi_reg_915 <= data_4_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_4_V_read43_phi_reg_915 <= ap_phi_reg_pp0_iter0_data_4_V_read43_phi_reg_915;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_5_V_read44_phi_reg_928 <= ap_phi_mux_data_5_V_read44_rewind_phi_fu_460_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_5_V_read44_phi_reg_928 <= data_5_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_5_V_read44_phi_reg_928 <= ap_phi_reg_pp0_iter0_data_5_V_read44_phi_reg_928;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_6_V_read45_phi_reg_941 <= ap_phi_mux_data_6_V_read45_rewind_phi_fu_474_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_6_V_read45_phi_reg_941 <= data_6_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_6_V_read45_phi_reg_941 <= ap_phi_reg_pp0_iter0_data_6_V_read45_phi_reg_941;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_7_V_read46_phi_reg_954 <= ap_phi_mux_data_7_V_read46_rewind_phi_fu_488_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_7_V_read46_phi_reg_954 <= data_7_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_7_V_read46_phi_reg_954 <= ap_phi_reg_pp0_iter0_data_7_V_read46_phi_reg_954;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_8_V_read47_phi_reg_967 <= ap_phi_mux_data_8_V_read47_rewind_phi_fu_502_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_8_V_read47_phi_reg_967 <= data_8_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_8_V_read47_phi_reg_967 <= ap_phi_reg_pp0_iter0_data_8_V_read47_phi_reg_967;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd0)) begin
            data_9_V_read48_phi_reg_980 <= ap_phi_mux_data_9_V_read48_rewind_phi_fu_516_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_374_p6 == 1'd1)) begin
            data_9_V_read48_phi_reg_980 <= data_9_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_9_V_read48_phi_reg_980 <= ap_phi_reg_pp0_iter0_data_9_V_read48_phi_reg_980;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        do_init_reg_370 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_370 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_index_0_i37_reg_848 <= select_ln154_fu_1601_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_index_0_i37_reg_848 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_0_V_write_assign18_reg_1405 <= acc_1_V_1_fu_1614_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_0_V_write_assign18_reg_1405 <= 14'd16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_1_V_write_assign20_reg_1391 <= acc_1_V_2_fu_1620_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_1_V_write_assign20_reg_1391 <= 14'd16352;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_2_V_write_assign22_reg_1377 <= acc_3_V_1_fu_1633_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_2_V_write_assign22_reg_1377 <= 14'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_3_V_write_assign24_reg_1363 <= acc_3_V_2_fu_1639_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_3_V_write_assign24_reg_1363 <= 14'd32;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_4_V_write_assign26_reg_1349 <= acc_5_V_1_fu_1652_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_4_V_write_assign26_reg_1349 <= 14'd16368;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_5_V_write_assign28_reg_1335 <= acc_5_V_2_fu_1658_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_5_V_write_assign28_reg_1335 <= 14'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_6_V_write_assign30_reg_1321 <= acc_7_V_1_fu_1671_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_6_V_write_assign30_reg_1321 <= 14'd16352;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_7_V_write_assign32_reg_1307 <= acc_7_V_2_fu_1677_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_7_V_write_assign32_reg_1307 <= 14'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_8_V_write_assign34_reg_1293 <= acc_9_V_1_fu_1690_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_8_V_write_assign34_reg_1293 <= 14'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_9_V_write_assign36_reg_1279 <= acc_9_V_2_fu_1696_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_9_V_write_assign36_reg_1279 <= 14'd32;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index38_reg_834 <= w_index_reg_1836;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        w_index38_reg_834 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_0_V_read39_rewind_reg_386 <= data_0_V_read39_phi_reg_863;
        data_10_V_read49_rewind_reg_526 <= data_10_V_read49_phi_reg_993;
        data_11_V_read50_rewind_reg_540 <= data_11_V_read50_phi_reg_1006;
        data_12_V_read51_rewind_reg_554 <= data_12_V_read51_phi_reg_1019;
        data_13_V_read52_rewind_reg_568 <= data_13_V_read52_phi_reg_1032;
        data_14_V_read53_rewind_reg_582 <= data_14_V_read53_phi_reg_1045;
        data_15_V_read54_rewind_reg_596 <= data_15_V_read54_phi_reg_1058;
        data_16_V_read55_rewind_reg_610 <= data_16_V_read55_phi_reg_1071;
        data_17_V_read56_rewind_reg_624 <= data_17_V_read56_phi_reg_1084;
        data_18_V_read57_rewind_reg_638 <= data_18_V_read57_phi_reg_1097;
        data_19_V_read58_rewind_reg_652 <= data_19_V_read58_phi_reg_1110;
        data_1_V_read40_rewind_reg_400 <= data_1_V_read40_phi_reg_876;
        data_20_V_read59_rewind_reg_666 <= data_20_V_read59_phi_reg_1123;
        data_21_V_read60_rewind_reg_680 <= data_21_V_read60_phi_reg_1136;
        data_22_V_read61_rewind_reg_694 <= data_22_V_read61_phi_reg_1149;
        data_23_V_read62_rewind_reg_708 <= data_23_V_read62_phi_reg_1162;
        data_24_V_read63_rewind_reg_722 <= data_24_V_read63_phi_reg_1175;
        data_25_V_read64_rewind_reg_736 <= data_25_V_read64_phi_reg_1188;
        data_26_V_read65_rewind_reg_750 <= data_26_V_read65_phi_reg_1201;
        data_27_V_read66_rewind_reg_764 <= data_27_V_read66_phi_reg_1214;
        data_28_V_read67_rewind_reg_778 <= data_28_V_read67_phi_reg_1227;
        data_29_V_read68_rewind_reg_792 <= data_29_V_read68_phi_reg_1240;
        data_2_V_read41_rewind_reg_414 <= data_2_V_read41_phi_reg_889;
        data_30_V_read69_rewind_reg_806 <= data_30_V_read69_phi_reg_1253;
        data_31_V_read70_rewind_reg_820 <= data_31_V_read70_phi_reg_1266;
        data_3_V_read42_rewind_reg_428 <= data_3_V_read42_phi_reg_902;
        data_4_V_read43_rewind_reg_442 <= data_4_V_read43_phi_reg_915;
        data_5_V_read44_rewind_reg_456 <= data_5_V_read44_phi_reg_928;
        data_6_V_read45_rewind_reg_470 <= data_6_V_read45_phi_reg_941;
        data_7_V_read46_rewind_reg_484 <= data_7_V_read46_phi_reg_954;
        data_8_V_read47_rewind_reg_498 <= data_8_V_read47_phi_reg_967;
        data_9_V_read48_rewind_reg_512 <= data_9_V_read48_phi_reg_980;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln135_reg_1841 <= icmp_ln135_fu_1453_p2;
        icmp_ln135_reg_1841_pp0_iter1_reg <= icmp_ln135_reg_1841;
        icmp_ln154_reg_1831 <= icmp_ln154_fu_1441_p2;
        in_index_reg_1826 <= in_index_fu_1425_p2;
        out_index_reg_1845 <= outidx_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln135_reg_1841_pp0_iter2_reg <= icmp_ln135_reg_1841_pp0_iter1_reg;
        out_index_reg_1845_pp0_iter2_reg <= out_index_reg_1845;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index_reg_1836 <= w_index_fu_1447_p2;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_0_V_read39_rewind_phi_fu_390_p6 = data_0_V_read39_phi_reg_863;
    end else begin
        ap_phi_mux_data_0_V_read39_rewind_phi_fu_390_p6 = data_0_V_read39_rewind_reg_386;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_10_V_read49_rewind_phi_fu_530_p6 = data_10_V_read49_phi_reg_993;
    end else begin
        ap_phi_mux_data_10_V_read49_rewind_phi_fu_530_p6 = data_10_V_read49_rewind_reg_526;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_11_V_read50_rewind_phi_fu_544_p6 = data_11_V_read50_phi_reg_1006;
    end else begin
        ap_phi_mux_data_11_V_read50_rewind_phi_fu_544_p6 = data_11_V_read50_rewind_reg_540;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_12_V_read51_rewind_phi_fu_558_p6 = data_12_V_read51_phi_reg_1019;
    end else begin
        ap_phi_mux_data_12_V_read51_rewind_phi_fu_558_p6 = data_12_V_read51_rewind_reg_554;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_13_V_read52_rewind_phi_fu_572_p6 = data_13_V_read52_phi_reg_1032;
    end else begin
        ap_phi_mux_data_13_V_read52_rewind_phi_fu_572_p6 = data_13_V_read52_rewind_reg_568;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_14_V_read53_rewind_phi_fu_586_p6 = data_14_V_read53_phi_reg_1045;
    end else begin
        ap_phi_mux_data_14_V_read53_rewind_phi_fu_586_p6 = data_14_V_read53_rewind_reg_582;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_15_V_read54_rewind_phi_fu_600_p6 = data_15_V_read54_phi_reg_1058;
    end else begin
        ap_phi_mux_data_15_V_read54_rewind_phi_fu_600_p6 = data_15_V_read54_rewind_reg_596;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_16_V_read55_rewind_phi_fu_614_p6 = data_16_V_read55_phi_reg_1071;
    end else begin
        ap_phi_mux_data_16_V_read55_rewind_phi_fu_614_p6 = data_16_V_read55_rewind_reg_610;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_17_V_read56_rewind_phi_fu_628_p6 = data_17_V_read56_phi_reg_1084;
    end else begin
        ap_phi_mux_data_17_V_read56_rewind_phi_fu_628_p6 = data_17_V_read56_rewind_reg_624;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_18_V_read57_rewind_phi_fu_642_p6 = data_18_V_read57_phi_reg_1097;
    end else begin
        ap_phi_mux_data_18_V_read57_rewind_phi_fu_642_p6 = data_18_V_read57_rewind_reg_638;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_19_V_read58_rewind_phi_fu_656_p6 = data_19_V_read58_phi_reg_1110;
    end else begin
        ap_phi_mux_data_19_V_read58_rewind_phi_fu_656_p6 = data_19_V_read58_rewind_reg_652;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_1_V_read40_rewind_phi_fu_404_p6 = data_1_V_read40_phi_reg_876;
    end else begin
        ap_phi_mux_data_1_V_read40_rewind_phi_fu_404_p6 = data_1_V_read40_rewind_reg_400;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_20_V_read59_rewind_phi_fu_670_p6 = data_20_V_read59_phi_reg_1123;
    end else begin
        ap_phi_mux_data_20_V_read59_rewind_phi_fu_670_p6 = data_20_V_read59_rewind_reg_666;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_21_V_read60_rewind_phi_fu_684_p6 = data_21_V_read60_phi_reg_1136;
    end else begin
        ap_phi_mux_data_21_V_read60_rewind_phi_fu_684_p6 = data_21_V_read60_rewind_reg_680;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_22_V_read61_rewind_phi_fu_698_p6 = data_22_V_read61_phi_reg_1149;
    end else begin
        ap_phi_mux_data_22_V_read61_rewind_phi_fu_698_p6 = data_22_V_read61_rewind_reg_694;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_23_V_read62_rewind_phi_fu_712_p6 = data_23_V_read62_phi_reg_1162;
    end else begin
        ap_phi_mux_data_23_V_read62_rewind_phi_fu_712_p6 = data_23_V_read62_rewind_reg_708;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_24_V_read63_rewind_phi_fu_726_p6 = data_24_V_read63_phi_reg_1175;
    end else begin
        ap_phi_mux_data_24_V_read63_rewind_phi_fu_726_p6 = data_24_V_read63_rewind_reg_722;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_25_V_read64_rewind_phi_fu_740_p6 = data_25_V_read64_phi_reg_1188;
    end else begin
        ap_phi_mux_data_25_V_read64_rewind_phi_fu_740_p6 = data_25_V_read64_rewind_reg_736;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_26_V_read65_rewind_phi_fu_754_p6 = data_26_V_read65_phi_reg_1201;
    end else begin
        ap_phi_mux_data_26_V_read65_rewind_phi_fu_754_p6 = data_26_V_read65_rewind_reg_750;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_27_V_read66_rewind_phi_fu_768_p6 = data_27_V_read66_phi_reg_1214;
    end else begin
        ap_phi_mux_data_27_V_read66_rewind_phi_fu_768_p6 = data_27_V_read66_rewind_reg_764;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_28_V_read67_rewind_phi_fu_782_p6 = data_28_V_read67_phi_reg_1227;
    end else begin
        ap_phi_mux_data_28_V_read67_rewind_phi_fu_782_p6 = data_28_V_read67_rewind_reg_778;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_29_V_read68_rewind_phi_fu_796_p6 = data_29_V_read68_phi_reg_1240;
    end else begin
        ap_phi_mux_data_29_V_read68_rewind_phi_fu_796_p6 = data_29_V_read68_rewind_reg_792;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_2_V_read41_rewind_phi_fu_418_p6 = data_2_V_read41_phi_reg_889;
    end else begin
        ap_phi_mux_data_2_V_read41_rewind_phi_fu_418_p6 = data_2_V_read41_rewind_reg_414;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_30_V_read69_rewind_phi_fu_810_p6 = data_30_V_read69_phi_reg_1253;
    end else begin
        ap_phi_mux_data_30_V_read69_rewind_phi_fu_810_p6 = data_30_V_read69_rewind_reg_806;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_31_V_read70_rewind_phi_fu_824_p6 = data_31_V_read70_phi_reg_1266;
    end else begin
        ap_phi_mux_data_31_V_read70_rewind_phi_fu_824_p6 = data_31_V_read70_rewind_reg_820;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_3_V_read42_rewind_phi_fu_432_p6 = data_3_V_read42_phi_reg_902;
    end else begin
        ap_phi_mux_data_3_V_read42_rewind_phi_fu_432_p6 = data_3_V_read42_rewind_reg_428;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_4_V_read43_rewind_phi_fu_446_p6 = data_4_V_read43_phi_reg_915;
    end else begin
        ap_phi_mux_data_4_V_read43_rewind_phi_fu_446_p6 = data_4_V_read43_rewind_reg_442;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_5_V_read44_rewind_phi_fu_460_p6 = data_5_V_read44_phi_reg_928;
    end else begin
        ap_phi_mux_data_5_V_read44_rewind_phi_fu_460_p6 = data_5_V_read44_rewind_reg_456;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_6_V_read45_rewind_phi_fu_474_p6 = data_6_V_read45_phi_reg_941;
    end else begin
        ap_phi_mux_data_6_V_read45_rewind_phi_fu_474_p6 = data_6_V_read45_rewind_reg_470;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_7_V_read46_rewind_phi_fu_488_p6 = data_7_V_read46_phi_reg_954;
    end else begin
        ap_phi_mux_data_7_V_read46_rewind_phi_fu_488_p6 = data_7_V_read46_rewind_reg_484;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_8_V_read47_rewind_phi_fu_502_p6 = data_8_V_read47_phi_reg_967;
    end else begin
        ap_phi_mux_data_8_V_read47_rewind_phi_fu_502_p6 = data_8_V_read47_rewind_reg_498;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1841 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_9_V_read48_rewind_phi_fu_516_p6 = data_9_V_read48_phi_reg_980;
    end else begin
        ap_phi_mux_data_9_V_read48_rewind_phi_fu_516_p6 = data_9_V_read48_rewind_reg_512;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_329)) begin
        if ((icmp_ln135_reg_1841 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_374_p6 = 1'd1;
        end else if ((icmp_ln135_reg_1841 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_374_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_374_p6 = do_init_reg_370;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_374_p6 = do_init_reg_370;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_329)) begin
        if ((icmp_ln135_reg_1841 == 1'd1)) begin
            ap_phi_mux_in_index_0_i37_phi_fu_852_p6 = 32'd0;
        end else if ((icmp_ln135_reg_1841 == 1'd0)) begin
            ap_phi_mux_in_index_0_i37_phi_fu_852_p6 = select_ln154_fu_1601_p3;
        end else begin
            ap_phi_mux_in_index_0_i37_phi_fu_852_p6 = in_index_0_i37_reg_848;
        end
    end else begin
        ap_phi_mux_in_index_0_i37_phi_fu_852_p6 = in_index_0_i37_reg_848;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_329)) begin
        if ((icmp_ln135_reg_1841 == 1'd1)) begin
            ap_phi_mux_w_index38_phi_fu_838_p6 = 6'd0;
        end else if ((icmp_ln135_reg_1841 == 1'd0)) begin
            ap_phi_mux_w_index38_phi_fu_838_p6 = w_index_reg_1836;
        end else begin
            ap_phi_mux_w_index38_phi_fu_838_p6 = w_index38_reg_834;
        end
    end else begin
        ap_phi_mux_w_index38_phi_fu_838_p6 = w_index38_reg_834;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_fu_1453_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_0 = acc_1_V_1_fu_1614_p3;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_1 = acc_1_V_2_fu_1620_p3;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_2 = acc_3_V_1_fu_1633_p3;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_3 = acc_3_V_2_fu_1639_p3;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_4 = acc_5_V_1_fu_1652_p3;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_5 = acc_5_V_2_fu_1658_p3;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_6 = acc_7_V_1_fu_1671_p3;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_7 = acc_7_V_2_fu_1677_p3;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_8 = acc_9_V_1_fu_1690_p3;
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1841_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_9 = acc_9_V_2_fu_1696_p3;
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1766_ce = 1'b1;
    end else begin
        grp_fu_1766_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1776_ce = 1'b1;
    end else begin
        grp_fu_1776_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1786_ce = 1'b1;
    end else begin
        grp_fu_1786_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1796_ce = 1'b1;
    end else begin
        grp_fu_1796_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1806_ce = 1'b1;
    end else begin
        grp_fu_1806_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outidx_ce0 = 1'b1;
    end else begin
        outidx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_V_ce0 = 1'b1;
    end else begin
        w11_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_V_1_fu_1614_p3 = ((out_index_reg_1845_pp0_iter2_reg[0:0] === 1'b1) ? res_0_V_write_assign18_reg_1405 : grp_fu_1766_p3);

assign acc_1_V_2_fu_1620_p3 = ((out_index_reg_1845_pp0_iter2_reg[0:0] === 1'b1) ? grp_fu_1766_p3 : res_1_V_write_assign20_reg_1391);

assign acc_3_V_1_fu_1633_p3 = ((out_index_reg_1845_pp0_iter2_reg[0:0] === 1'b1) ? res_2_V_write_assign22_reg_1377 : grp_fu_1776_p3);

assign acc_3_V_2_fu_1639_p3 = ((out_index_reg_1845_pp0_iter2_reg[0:0] === 1'b1) ? grp_fu_1776_p3 : res_3_V_write_assign24_reg_1363);

assign acc_5_V_1_fu_1652_p3 = ((out_index_reg_1845_pp0_iter2_reg[0:0] === 1'b1) ? res_4_V_write_assign26_reg_1349 : grp_fu_1786_p3);

assign acc_5_V_2_fu_1658_p3 = ((out_index_reg_1845_pp0_iter2_reg[0:0] === 1'b1) ? grp_fu_1786_p3 : res_5_V_write_assign28_reg_1335);

assign acc_7_V_1_fu_1671_p3 = ((out_index_reg_1845_pp0_iter2_reg[0:0] === 1'b1) ? res_6_V_write_assign30_reg_1321 : grp_fu_1796_p3);

assign acc_7_V_2_fu_1677_p3 = ((out_index_reg_1845_pp0_iter2_reg[0:0] === 1'b1) ? grp_fu_1796_p3 : res_7_V_write_assign32_reg_1307);

assign acc_9_V_1_fu_1690_p3 = ((out_index_reg_1845_pp0_iter2_reg[0:0] === 1'b1) ? res_8_V_write_assign34_reg_1293 : grp_fu_1806_p3);

assign acc_9_V_2_fu_1696_p3 = ((out_index_reg_1845_pp0_iter2_reg[0:0] === 1'b1) ? grp_fu_1806_p3 : res_9_V_write_assign36_reg_1279);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_329 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_41 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_data_0_V_read39_phi_reg_863 = 'bx;

assign ap_phi_reg_pp0_iter0_data_10_V_read49_phi_reg_993 = 'bx;

assign ap_phi_reg_pp0_iter0_data_11_V_read50_phi_reg_1006 = 'bx;

assign ap_phi_reg_pp0_iter0_data_12_V_read51_phi_reg_1019 = 'bx;

assign ap_phi_reg_pp0_iter0_data_13_V_read52_phi_reg_1032 = 'bx;

assign ap_phi_reg_pp0_iter0_data_14_V_read53_phi_reg_1045 = 'bx;

assign ap_phi_reg_pp0_iter0_data_15_V_read54_phi_reg_1058 = 'bx;

assign ap_phi_reg_pp0_iter0_data_16_V_read55_phi_reg_1071 = 'bx;

assign ap_phi_reg_pp0_iter0_data_17_V_read56_phi_reg_1084 = 'bx;

assign ap_phi_reg_pp0_iter0_data_18_V_read57_phi_reg_1097 = 'bx;

assign ap_phi_reg_pp0_iter0_data_19_V_read58_phi_reg_1110 = 'bx;

assign ap_phi_reg_pp0_iter0_data_1_V_read40_phi_reg_876 = 'bx;

assign ap_phi_reg_pp0_iter0_data_20_V_read59_phi_reg_1123 = 'bx;

assign ap_phi_reg_pp0_iter0_data_21_V_read60_phi_reg_1136 = 'bx;

assign ap_phi_reg_pp0_iter0_data_22_V_read61_phi_reg_1149 = 'bx;

assign ap_phi_reg_pp0_iter0_data_23_V_read62_phi_reg_1162 = 'bx;

assign ap_phi_reg_pp0_iter0_data_24_V_read63_phi_reg_1175 = 'bx;

assign ap_phi_reg_pp0_iter0_data_25_V_read64_phi_reg_1188 = 'bx;

assign ap_phi_reg_pp0_iter0_data_26_V_read65_phi_reg_1201 = 'bx;

assign ap_phi_reg_pp0_iter0_data_27_V_read66_phi_reg_1214 = 'bx;

assign ap_phi_reg_pp0_iter0_data_28_V_read67_phi_reg_1227 = 'bx;

assign ap_phi_reg_pp0_iter0_data_29_V_read68_phi_reg_1240 = 'bx;

assign ap_phi_reg_pp0_iter0_data_2_V_read41_phi_reg_889 = 'bx;

assign ap_phi_reg_pp0_iter0_data_30_V_read69_phi_reg_1253 = 'bx;

assign ap_phi_reg_pp0_iter0_data_31_V_read70_phi_reg_1266 = 'bx;

assign ap_phi_reg_pp0_iter0_data_3_V_read42_phi_reg_902 = 'bx;

assign ap_phi_reg_pp0_iter0_data_4_V_read43_phi_reg_915 = 'bx;

assign ap_phi_reg_pp0_iter0_data_5_V_read44_phi_reg_928 = 'bx;

assign ap_phi_reg_pp0_iter0_data_6_V_read45_phi_reg_941 = 'bx;

assign ap_phi_reg_pp0_iter0_data_7_V_read46_phi_reg_954 = 'bx;

assign ap_phi_reg_pp0_iter0_data_8_V_read47_phi_reg_967 = 'bx;

assign ap_phi_reg_pp0_iter0_data_9_V_read48_phi_reg_980 = 'bx;

assign grp_fu_1766_p0 = zext_ln1116_fu_1537_p1;

assign grp_fu_1766_p2 = ((out_index_reg_1845_pp0_iter2_reg[0:0] === 1'b1) ? res_1_V_write_assign20_reg_1391 : res_0_V_write_assign18_reg_1405);

assign grp_fu_1776_p0 = zext_ln1116_fu_1537_p1;

assign grp_fu_1776_p2 = ((out_index_reg_1845_pp0_iter2_reg[0:0] === 1'b1) ? res_3_V_write_assign24_reg_1363 : res_2_V_write_assign22_reg_1377);

assign grp_fu_1786_p0 = zext_ln1116_fu_1537_p1;

assign grp_fu_1786_p2 = ((out_index_reg_1845_pp0_iter2_reg[0:0] === 1'b1) ? res_5_V_write_assign28_reg_1335 : res_4_V_write_assign26_reg_1349);

assign grp_fu_1796_p0 = zext_ln1116_fu_1537_p1;

assign grp_fu_1796_p2 = ((out_index_reg_1845_pp0_iter2_reg[0:0] === 1'b1) ? res_7_V_write_assign32_reg_1307 : res_6_V_write_assign30_reg_1321);

assign grp_fu_1806_p0 = zext_ln1116_fu_1537_p1;

assign grp_fu_1806_p2 = ((out_index_reg_1845_pp0_iter2_reg[0:0] === 1'b1) ? res_9_V_write_assign36_reg_1279 : res_8_V_write_assign34_reg_1293);

assign icmp_ln135_fu_1453_p2 = ((ap_phi_mux_w_index38_phi_fu_838_p6 == 6'd63) ? 1'b1 : 1'b0);

assign icmp_ln154_fu_1441_p2 = (($signed(tmp_430_fu_1431_p4) > $signed(27'd0)) ? 1'b1 : 1'b0);

assign in_index_fu_1425_p2 = (32'd1 + ap_phi_mux_in_index_0_i37_phi_fu_852_p6);

assign outidx_address0 = zext_ln139_fu_1419_p1;

assign select_ln154_fu_1601_p3 = ((icmp_ln154_reg_1831[0:0] === 1'b1) ? 32'd0 : in_index_reg_1826);

assign tmp_430_fu_1431_p4 = {{in_index_fu_1425_p2[31:5]}};

assign tmp_523_fu_1463_p33 = in_index_0_i37_reg_848[4:0];

assign tmp_524_fu_1545_p4 = {{w11_V_q0[7:4]}};

assign tmp_525_fu_1559_p4 = {{w11_V_q0[11:8]}};

assign tmp_526_fu_1573_p4 = {{w11_V_q0[15:12]}};

assign tmp_527_fu_1587_p4 = {{w11_V_q0[19:16]}};

assign trunc_ln145_1_fu_1533_p1 = w11_V_q0[3:0];

assign w11_V_address0 = zext_ln139_fu_1419_p1;

assign w_index_fu_1447_p2 = (6'd1 + ap_phi_mux_w_index38_phi_fu_838_p6);

assign zext_ln1116_fu_1537_p1 = tmp_523_fu_1463_p34;

assign zext_ln139_fu_1419_p1 = ap_phi_mux_w_index38_phi_fu_838_p6;

endmodule //dense_wrapper_ap_ufixed_4_0_4_0_0_ap_fixed_14_7_5_3_0_config11_s
