// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_wrapper_ap_ufixed_4_0_4_0_0_ap_fixed_14_7_5_3_0_config11_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        data_20_V_read,
        data_21_V_read,
        data_22_V_read,
        data_23_V_read,
        data_24_V_read,
        data_25_V_read,
        data_26_V_read,
        data_27_V_read,
        data_28_V_read,
        data_29_V_read,
        data_30_V_read,
        data_31_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [3:0] data_0_V_read;
input  [3:0] data_1_V_read;
input  [3:0] data_2_V_read;
input  [3:0] data_3_V_read;
input  [3:0] data_4_V_read;
input  [3:0] data_5_V_read;
input  [3:0] data_6_V_read;
input  [3:0] data_7_V_read;
input  [3:0] data_8_V_read;
input  [3:0] data_9_V_read;
input  [3:0] data_10_V_read;
input  [3:0] data_11_V_read;
input  [3:0] data_12_V_read;
input  [3:0] data_13_V_read;
input  [3:0] data_14_V_read;
input  [3:0] data_15_V_read;
input  [3:0] data_16_V_read;
input  [3:0] data_17_V_read;
input  [3:0] data_18_V_read;
input  [3:0] data_19_V_read;
input  [3:0] data_20_V_read;
input  [3:0] data_21_V_read;
input  [3:0] data_22_V_read;
input  [3:0] data_23_V_read;
input  [3:0] data_24_V_read;
input  [3:0] data_25_V_read;
input  [3:0] data_26_V_read;
input  [3:0] data_27_V_read;
input  [3:0] data_28_V_read;
input  [3:0] data_29_V_read;
input  [3:0] data_30_V_read;
input  [3:0] data_31_V_read;
output  [13:0] ap_return_0;
output  [13:0] ap_return_1;
output  [13:0] ap_return_2;
output  [13:0] ap_return_3;
output  [13:0] ap_return_4;
output  [13:0] ap_return_5;
output  [13:0] ap_return_6;
output  [13:0] ap_return_7;
output  [13:0] ap_return_8;
output  [13:0] ap_return_9;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[13:0] ap_return_0;
reg[13:0] ap_return_1;
reg[13:0] ap_return_2;
reg[13:0] ap_return_3;
reg[13:0] ap_return_4;
reg[13:0] ap_return_5;
reg[13:0] ap_return_6;
reg[13:0] ap_return_7;
reg[13:0] ap_return_8;
reg[13:0] ap_return_9;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln135_fu_1455_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] outidx_address0;
reg    outidx_ce0;
wire   [0:0] outidx_q0;
wire   [5:0] w11_V_address0;
reg    w11_V_ce0;
wire   [19:0] w11_V_q0;
reg   [0:0] do_init_reg_372;
reg   [3:0] data_0_V_read39_rewind_reg_388;
reg   [3:0] data_1_V_read40_rewind_reg_402;
reg   [3:0] data_2_V_read41_rewind_reg_416;
reg   [3:0] data_3_V_read42_rewind_reg_430;
reg   [3:0] data_4_V_read43_rewind_reg_444;
reg   [3:0] data_5_V_read44_rewind_reg_458;
reg   [3:0] data_6_V_read45_rewind_reg_472;
reg   [3:0] data_7_V_read46_rewind_reg_486;
reg   [3:0] data_8_V_read47_rewind_reg_500;
reg   [3:0] data_9_V_read48_rewind_reg_514;
reg   [3:0] data_10_V_read49_rewind_reg_528;
reg   [3:0] data_11_V_read50_rewind_reg_542;
reg   [3:0] data_12_V_read51_rewind_reg_556;
reg   [3:0] data_13_V_read52_rewind_reg_570;
reg   [3:0] data_14_V_read53_rewind_reg_584;
reg   [3:0] data_15_V_read54_rewind_reg_598;
reg   [3:0] data_16_V_read55_rewind_reg_612;
reg   [3:0] data_17_V_read56_rewind_reg_626;
reg   [3:0] data_18_V_read57_rewind_reg_640;
reg   [3:0] data_19_V_read58_rewind_reg_654;
reg   [3:0] data_20_V_read59_rewind_reg_668;
reg   [3:0] data_21_V_read60_rewind_reg_682;
reg   [3:0] data_22_V_read61_rewind_reg_696;
reg   [3:0] data_23_V_read62_rewind_reg_710;
reg   [3:0] data_24_V_read63_rewind_reg_724;
reg   [3:0] data_25_V_read64_rewind_reg_738;
reg   [3:0] data_26_V_read65_rewind_reg_752;
reg   [3:0] data_27_V_read66_rewind_reg_766;
reg   [3:0] data_28_V_read67_rewind_reg_780;
reg   [3:0] data_29_V_read68_rewind_reg_794;
reg   [3:0] data_30_V_read69_rewind_reg_808;
reg   [3:0] data_31_V_read70_rewind_reg_822;
reg   [5:0] w_index38_reg_836;
reg   [31:0] in_index_0_i37_reg_850;
reg   [3:0] data_0_V_read39_phi_reg_865;
reg   [3:0] data_1_V_read40_phi_reg_878;
reg   [3:0] data_2_V_read41_phi_reg_891;
reg   [3:0] data_3_V_read42_phi_reg_904;
reg   [3:0] data_4_V_read43_phi_reg_917;
reg   [3:0] data_5_V_read44_phi_reg_930;
reg   [3:0] data_6_V_read45_phi_reg_943;
reg   [3:0] data_7_V_read46_phi_reg_956;
reg   [3:0] data_8_V_read47_phi_reg_969;
reg   [3:0] data_9_V_read48_phi_reg_982;
reg   [3:0] data_10_V_read49_phi_reg_995;
reg   [3:0] data_11_V_read50_phi_reg_1008;
reg   [3:0] data_12_V_read51_phi_reg_1021;
reg   [3:0] data_13_V_read52_phi_reg_1034;
reg   [3:0] data_14_V_read53_phi_reg_1047;
reg   [3:0] data_15_V_read54_phi_reg_1060;
reg   [3:0] data_16_V_read55_phi_reg_1073;
reg   [3:0] data_17_V_read56_phi_reg_1086;
reg   [3:0] data_18_V_read57_phi_reg_1099;
reg   [3:0] data_19_V_read58_phi_reg_1112;
reg   [3:0] data_20_V_read59_phi_reg_1125;
reg   [3:0] data_21_V_read60_phi_reg_1138;
reg   [3:0] data_22_V_read61_phi_reg_1151;
reg   [3:0] data_23_V_read62_phi_reg_1164;
reg   [3:0] data_24_V_read63_phi_reg_1177;
reg   [3:0] data_25_V_read64_phi_reg_1190;
reg   [3:0] data_26_V_read65_phi_reg_1203;
reg   [3:0] data_27_V_read66_phi_reg_1216;
reg   [3:0] data_28_V_read67_phi_reg_1229;
reg   [3:0] data_29_V_read68_phi_reg_1242;
reg   [3:0] data_30_V_read69_phi_reg_1255;
reg   [3:0] data_31_V_read70_phi_reg_1268;
reg   [13:0] res_9_V_write_assign36_reg_1281;
reg   [13:0] res_8_V_write_assign34_reg_1295;
reg   [13:0] res_7_V_write_assign32_reg_1309;
reg   [13:0] res_6_V_write_assign30_reg_1323;
reg   [13:0] res_5_V_write_assign28_reg_1337;
reg   [13:0] res_4_V_write_assign26_reg_1351;
reg   [13:0] res_3_V_write_assign24_reg_1365;
reg   [13:0] res_2_V_write_assign22_reg_1379;
reg   [13:0] res_1_V_write_assign20_reg_1393;
reg   [13:0] res_0_V_write_assign18_reg_1407;
wire   [31:0] in_index_fu_1427_p2;
reg   [31:0] in_index_reg_1828;
wire   [0:0] icmp_ln154_fu_1443_p2;
reg   [0:0] icmp_ln154_reg_1833;
wire   [5:0] w_index_fu_1449_p2;
reg   [5:0] w_index_reg_1838;
reg   [0:0] icmp_ln135_reg_1843;
reg   [0:0] icmp_ln135_reg_1843_pp0_iter1_reg;
reg   [0:0] icmp_ln135_reg_1843_pp0_iter2_reg;
reg   [0:0] out_index_reg_1847;
reg   [0:0] out_index_reg_1847_pp0_iter2_reg;
wire   [7:0] zext_ln1116_fu_1539_p1;
wire   [31:0] select_ln154_fu_1603_p3;
reg    ap_enable_reg_pp0_iter1;
wire   [13:0] acc_1_V_1_fu_1616_p3;
reg    ap_enable_reg_pp0_iter3;
wire   [13:0] acc_1_V_2_fu_1622_p3;
wire   [13:0] acc_3_V_1_fu_1635_p3;
wire   [13:0] acc_3_V_2_fu_1641_p3;
wire   [13:0] acc_5_V_1_fu_1654_p3;
wire   [13:0] acc_5_V_2_fu_1660_p3;
wire   [13:0] acc_7_V_1_fu_1673_p3;
wire   [13:0] acc_7_V_2_fu_1679_p3;
wire   [13:0] acc_9_V_1_fu_1692_p3;
wire   [13:0] acc_9_V_2_fu_1698_p3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] ap_phi_mux_do_init_phi_fu_376_p6;
wire    ap_block_pp0_stage0;
reg   [3:0] ap_phi_mux_data_0_V_read39_rewind_phi_fu_392_p6;
reg   [3:0] ap_phi_mux_data_1_V_read40_rewind_phi_fu_406_p6;
reg   [3:0] ap_phi_mux_data_2_V_read41_rewind_phi_fu_420_p6;
reg   [3:0] ap_phi_mux_data_3_V_read42_rewind_phi_fu_434_p6;
reg   [3:0] ap_phi_mux_data_4_V_read43_rewind_phi_fu_448_p6;
reg   [3:0] ap_phi_mux_data_5_V_read44_rewind_phi_fu_462_p6;
reg   [3:0] ap_phi_mux_data_6_V_read45_rewind_phi_fu_476_p6;
reg   [3:0] ap_phi_mux_data_7_V_read46_rewind_phi_fu_490_p6;
reg   [3:0] ap_phi_mux_data_8_V_read47_rewind_phi_fu_504_p6;
reg   [3:0] ap_phi_mux_data_9_V_read48_rewind_phi_fu_518_p6;
reg   [3:0] ap_phi_mux_data_10_V_read49_rewind_phi_fu_532_p6;
reg   [3:0] ap_phi_mux_data_11_V_read50_rewind_phi_fu_546_p6;
reg   [3:0] ap_phi_mux_data_12_V_read51_rewind_phi_fu_560_p6;
reg   [3:0] ap_phi_mux_data_13_V_read52_rewind_phi_fu_574_p6;
reg   [3:0] ap_phi_mux_data_14_V_read53_rewind_phi_fu_588_p6;
reg   [3:0] ap_phi_mux_data_15_V_read54_rewind_phi_fu_602_p6;
reg   [3:0] ap_phi_mux_data_16_V_read55_rewind_phi_fu_616_p6;
reg   [3:0] ap_phi_mux_data_17_V_read56_rewind_phi_fu_630_p6;
reg   [3:0] ap_phi_mux_data_18_V_read57_rewind_phi_fu_644_p6;
reg   [3:0] ap_phi_mux_data_19_V_read58_rewind_phi_fu_658_p6;
reg   [3:0] ap_phi_mux_data_20_V_read59_rewind_phi_fu_672_p6;
reg   [3:0] ap_phi_mux_data_21_V_read60_rewind_phi_fu_686_p6;
reg   [3:0] ap_phi_mux_data_22_V_read61_rewind_phi_fu_700_p6;
reg   [3:0] ap_phi_mux_data_23_V_read62_rewind_phi_fu_714_p6;
reg   [3:0] ap_phi_mux_data_24_V_read63_rewind_phi_fu_728_p6;
reg   [3:0] ap_phi_mux_data_25_V_read64_rewind_phi_fu_742_p6;
reg   [3:0] ap_phi_mux_data_26_V_read65_rewind_phi_fu_756_p6;
reg   [3:0] ap_phi_mux_data_27_V_read66_rewind_phi_fu_770_p6;
reg   [3:0] ap_phi_mux_data_28_V_read67_rewind_phi_fu_784_p6;
reg   [3:0] ap_phi_mux_data_29_V_read68_rewind_phi_fu_798_p6;
reg   [3:0] ap_phi_mux_data_30_V_read69_rewind_phi_fu_812_p6;
reg   [3:0] ap_phi_mux_data_31_V_read70_rewind_phi_fu_826_p6;
reg   [5:0] ap_phi_mux_w_index38_phi_fu_840_p6;
reg   [31:0] ap_phi_mux_in_index_0_i37_phi_fu_854_p6;
wire   [3:0] ap_phi_reg_pp0_iter0_data_0_V_read39_phi_reg_865;
wire   [3:0] ap_phi_reg_pp0_iter0_data_1_V_read40_phi_reg_878;
wire   [3:0] ap_phi_reg_pp0_iter0_data_2_V_read41_phi_reg_891;
wire   [3:0] ap_phi_reg_pp0_iter0_data_3_V_read42_phi_reg_904;
wire   [3:0] ap_phi_reg_pp0_iter0_data_4_V_read43_phi_reg_917;
wire   [3:0] ap_phi_reg_pp0_iter0_data_5_V_read44_phi_reg_930;
wire   [3:0] ap_phi_reg_pp0_iter0_data_6_V_read45_phi_reg_943;
wire   [3:0] ap_phi_reg_pp0_iter0_data_7_V_read46_phi_reg_956;
wire   [3:0] ap_phi_reg_pp0_iter0_data_8_V_read47_phi_reg_969;
wire   [3:0] ap_phi_reg_pp0_iter0_data_9_V_read48_phi_reg_982;
wire   [3:0] ap_phi_reg_pp0_iter0_data_10_V_read49_phi_reg_995;
wire   [3:0] ap_phi_reg_pp0_iter0_data_11_V_read50_phi_reg_1008;
wire   [3:0] ap_phi_reg_pp0_iter0_data_12_V_read51_phi_reg_1021;
wire   [3:0] ap_phi_reg_pp0_iter0_data_13_V_read52_phi_reg_1034;
wire   [3:0] ap_phi_reg_pp0_iter0_data_14_V_read53_phi_reg_1047;
wire   [3:0] ap_phi_reg_pp0_iter0_data_15_V_read54_phi_reg_1060;
wire   [3:0] ap_phi_reg_pp0_iter0_data_16_V_read55_phi_reg_1073;
wire   [3:0] ap_phi_reg_pp0_iter0_data_17_V_read56_phi_reg_1086;
wire   [3:0] ap_phi_reg_pp0_iter0_data_18_V_read57_phi_reg_1099;
wire   [3:0] ap_phi_reg_pp0_iter0_data_19_V_read58_phi_reg_1112;
wire   [3:0] ap_phi_reg_pp0_iter0_data_20_V_read59_phi_reg_1125;
wire   [3:0] ap_phi_reg_pp0_iter0_data_21_V_read60_phi_reg_1138;
wire   [3:0] ap_phi_reg_pp0_iter0_data_22_V_read61_phi_reg_1151;
wire   [3:0] ap_phi_reg_pp0_iter0_data_23_V_read62_phi_reg_1164;
wire   [3:0] ap_phi_reg_pp0_iter0_data_24_V_read63_phi_reg_1177;
wire   [3:0] ap_phi_reg_pp0_iter0_data_25_V_read64_phi_reg_1190;
wire   [3:0] ap_phi_reg_pp0_iter0_data_26_V_read65_phi_reg_1203;
wire   [3:0] ap_phi_reg_pp0_iter0_data_27_V_read66_phi_reg_1216;
wire   [3:0] ap_phi_reg_pp0_iter0_data_28_V_read67_phi_reg_1229;
wire   [3:0] ap_phi_reg_pp0_iter0_data_29_V_read68_phi_reg_1242;
wire   [3:0] ap_phi_reg_pp0_iter0_data_30_V_read69_phi_reg_1255;
wire   [3:0] ap_phi_reg_pp0_iter0_data_31_V_read70_phi_reg_1268;
wire   [63:0] zext_ln139_fu_1421_p1;
wire   [26:0] tmp_430_fu_1433_p4;
wire   [4:0] tmp_523_fu_1465_p33;
wire   [3:0] tmp_523_fu_1465_p34;
wire  signed [3:0] trunc_ln145_1_fu_1535_p1;
wire  signed [3:0] tmp_524_fu_1547_p4;
wire  signed [3:0] tmp_525_fu_1561_p4;
wire  signed [3:0] tmp_526_fu_1575_p4;
wire  signed [3:0] tmp_527_fu_1589_p4;
wire  signed [13:0] grp_fu_1768_p3;
wire  signed [13:0] grp_fu_1778_p3;
wire  signed [13:0] grp_fu_1788_p3;
wire  signed [13:0] grp_fu_1798_p3;
wire  signed [13:0] grp_fu_1808_p3;
wire   [3:0] grp_fu_1768_p0;
wire   [13:0] grp_fu_1768_p2;
wire   [3:0] grp_fu_1778_p0;
wire   [13:0] grp_fu_1778_p2;
wire   [3:0] grp_fu_1788_p0;
wire   [13:0] grp_fu_1788_p2;
wire   [3:0] grp_fu_1798_p0;
wire   [13:0] grp_fu_1798_p2;
wire   [3:0] grp_fu_1808_p0;
wire   [13:0] grp_fu_1808_p2;
reg    grp_fu_1768_ce;
reg    grp_fu_1778_ce;
reg    grp_fu_1788_ce;
reg    grp_fu_1798_ce;
reg    grp_fu_1808_ce;
reg   [13:0] ap_return_0_preg;
reg   [13:0] ap_return_1_preg;
reg   [13:0] ap_return_2_preg;
reg   [13:0] ap_return_3_preg;
reg   [13:0] ap_return_4_preg;
reg   [13:0] ap_return_5_preg;
reg   [13:0] ap_return_6_preg;
reg   [13:0] ap_return_7_preg;
reg   [13:0] ap_return_8_preg;
reg   [13:0] ap_return_9_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_329;
reg    ap_condition_41;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_return_0_preg = 14'd0;
#0 ap_return_1_preg = 14'd0;
#0 ap_return_2_preg = 14'd0;
#0 ap_return_3_preg = 14'd0;
#0 ap_return_4_preg = 14'd0;
#0 ap_return_5_preg = 14'd0;
#0 ap_return_6_preg = 14'd0;
#0 ap_return_7_preg = 14'd0;
#0 ap_return_8_preg = 14'd0;
#0 ap_return_9_preg = 14'd0;
end

dense_wrapper_ap_ufixed_4_0_4_0_0_ap_fixed_14_7_5_3_0_config11_s_outidx #(
    .DataWidth( 1 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
outidx_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx_address0),
    .ce0(outidx_ce0),
    .q0(outidx_q0)
);

dense_wrapper_ap_ufixed_4_0_4_0_0_ap_fixed_14_7_5_3_0_config11_s_w11_V #(
    .DataWidth( 20 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
w11_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w11_V_address0),
    .ce0(w11_V_ce0),
    .q0(w11_V_q0)
);

myproject_axi_mux_325_4_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 4 ),
    .din3_WIDTH( 4 ),
    .din4_WIDTH( 4 ),
    .din5_WIDTH( 4 ),
    .din6_WIDTH( 4 ),
    .din7_WIDTH( 4 ),
    .din8_WIDTH( 4 ),
    .din9_WIDTH( 4 ),
    .din10_WIDTH( 4 ),
    .din11_WIDTH( 4 ),
    .din12_WIDTH( 4 ),
    .din13_WIDTH( 4 ),
    .din14_WIDTH( 4 ),
    .din15_WIDTH( 4 ),
    .din16_WIDTH( 4 ),
    .din17_WIDTH( 4 ),
    .din18_WIDTH( 4 ),
    .din19_WIDTH( 4 ),
    .din20_WIDTH( 4 ),
    .din21_WIDTH( 4 ),
    .din22_WIDTH( 4 ),
    .din23_WIDTH( 4 ),
    .din24_WIDTH( 4 ),
    .din25_WIDTH( 4 ),
    .din26_WIDTH( 4 ),
    .din27_WIDTH( 4 ),
    .din28_WIDTH( 4 ),
    .din29_WIDTH( 4 ),
    .din30_WIDTH( 4 ),
    .din31_WIDTH( 4 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 4 ))
myproject_axi_mux_325_4_1_1_U2325(
    .din0(data_0_V_read39_phi_reg_865),
    .din1(data_1_V_read40_phi_reg_878),
    .din2(data_2_V_read41_phi_reg_891),
    .din3(data_3_V_read42_phi_reg_904),
    .din4(data_4_V_read43_phi_reg_917),
    .din5(data_5_V_read44_phi_reg_930),
    .din6(data_6_V_read45_phi_reg_943),
    .din7(data_7_V_read46_phi_reg_956),
    .din8(data_8_V_read47_phi_reg_969),
    .din9(data_9_V_read48_phi_reg_982),
    .din10(data_10_V_read49_phi_reg_995),
    .din11(data_11_V_read50_phi_reg_1008),
    .din12(data_12_V_read51_phi_reg_1021),
    .din13(data_13_V_read52_phi_reg_1034),
    .din14(data_14_V_read53_phi_reg_1047),
    .din15(data_15_V_read54_phi_reg_1060),
    .din16(data_16_V_read55_phi_reg_1073),
    .din17(data_17_V_read56_phi_reg_1086),
    .din18(data_18_V_read57_phi_reg_1099),
    .din19(data_19_V_read58_phi_reg_1112),
    .din20(data_20_V_read59_phi_reg_1125),
    .din21(data_21_V_read60_phi_reg_1138),
    .din22(data_22_V_read61_phi_reg_1151),
    .din23(data_23_V_read62_phi_reg_1164),
    .din24(data_24_V_read63_phi_reg_1177),
    .din25(data_25_V_read64_phi_reg_1190),
    .din26(data_26_V_read65_phi_reg_1203),
    .din27(data_27_V_read66_phi_reg_1216),
    .din28(data_28_V_read67_phi_reg_1229),
    .din29(data_29_V_read68_phi_reg_1242),
    .din30(data_30_V_read69_phi_reg_1255),
    .din31(data_31_V_read70_phi_reg_1268),
    .din32(tmp_523_fu_1465_p33),
    .dout(tmp_523_fu_1465_p34)
);

myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1_U2326(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1768_p0),
    .din1(trunc_ln145_1_fu_1535_p1),
    .din2(grp_fu_1768_p2),
    .ce(grp_fu_1768_ce),
    .dout(grp_fu_1768_p3)
);

myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1_U2327(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1778_p0),
    .din1(tmp_524_fu_1547_p4),
    .din2(grp_fu_1778_p2),
    .ce(grp_fu_1778_ce),
    .dout(grp_fu_1778_p3)
);

myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1_U2328(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1788_p0),
    .din1(tmp_525_fu_1561_p4),
    .din2(grp_fu_1788_p2),
    .ce(grp_fu_1788_ce),
    .dout(grp_fu_1788_p3)
);

myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1_U2329(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1798_p0),
    .din1(tmp_526_fu_1575_p4),
    .din2(grp_fu_1798_p2),
    .ce(grp_fu_1798_ce),
    .dout(grp_fu_1798_p3)
);

myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 14 ),
    .dout_WIDTH( 14 ))
myproject_axi_mac_muladd_4ns_4s_14ns_14_3_1_U2330(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1808_p0),
    .din1(tmp_527_fu_1589_p4),
    .din2(grp_fu_1808_p2),
    .ce(grp_fu_1808_ce),
    .dout(grp_fu_1808_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_0_preg <= acc_1_V_1_fu_1616_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_1_preg <= acc_1_V_2_fu_1622_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_2_preg <= acc_3_V_1_fu_1635_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_3_preg <= acc_3_V_2_fu_1641_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_4_preg <= acc_5_V_1_fu_1654_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_5_preg <= acc_5_V_2_fu_1660_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_6_preg <= acc_7_V_1_fu_1673_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_7_preg <= acc_7_V_2_fu_1679_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_8_preg <= acc_9_V_1_fu_1692_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 14'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_9_preg <= acc_9_V_2_fu_1698_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_0_V_read39_phi_reg_865 <= ap_phi_mux_data_0_V_read39_rewind_phi_fu_392_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_0_V_read39_phi_reg_865 <= data_0_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_0_V_read39_phi_reg_865 <= ap_phi_reg_pp0_iter0_data_0_V_read39_phi_reg_865;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_10_V_read49_phi_reg_995 <= ap_phi_mux_data_10_V_read49_rewind_phi_fu_532_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_10_V_read49_phi_reg_995 <= data_10_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_10_V_read49_phi_reg_995 <= ap_phi_reg_pp0_iter0_data_10_V_read49_phi_reg_995;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_11_V_read50_phi_reg_1008 <= ap_phi_mux_data_11_V_read50_rewind_phi_fu_546_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_11_V_read50_phi_reg_1008 <= data_11_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_11_V_read50_phi_reg_1008 <= ap_phi_reg_pp0_iter0_data_11_V_read50_phi_reg_1008;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_12_V_read51_phi_reg_1021 <= ap_phi_mux_data_12_V_read51_rewind_phi_fu_560_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_12_V_read51_phi_reg_1021 <= data_12_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_12_V_read51_phi_reg_1021 <= ap_phi_reg_pp0_iter0_data_12_V_read51_phi_reg_1021;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_13_V_read52_phi_reg_1034 <= ap_phi_mux_data_13_V_read52_rewind_phi_fu_574_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_13_V_read52_phi_reg_1034 <= data_13_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_13_V_read52_phi_reg_1034 <= ap_phi_reg_pp0_iter0_data_13_V_read52_phi_reg_1034;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_14_V_read53_phi_reg_1047 <= ap_phi_mux_data_14_V_read53_rewind_phi_fu_588_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_14_V_read53_phi_reg_1047 <= data_14_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_14_V_read53_phi_reg_1047 <= ap_phi_reg_pp0_iter0_data_14_V_read53_phi_reg_1047;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_15_V_read54_phi_reg_1060 <= ap_phi_mux_data_15_V_read54_rewind_phi_fu_602_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_15_V_read54_phi_reg_1060 <= data_15_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_15_V_read54_phi_reg_1060 <= ap_phi_reg_pp0_iter0_data_15_V_read54_phi_reg_1060;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_16_V_read55_phi_reg_1073 <= ap_phi_mux_data_16_V_read55_rewind_phi_fu_616_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_16_V_read55_phi_reg_1073 <= data_16_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_16_V_read55_phi_reg_1073 <= ap_phi_reg_pp0_iter0_data_16_V_read55_phi_reg_1073;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_17_V_read56_phi_reg_1086 <= ap_phi_mux_data_17_V_read56_rewind_phi_fu_630_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_17_V_read56_phi_reg_1086 <= data_17_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_17_V_read56_phi_reg_1086 <= ap_phi_reg_pp0_iter0_data_17_V_read56_phi_reg_1086;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_18_V_read57_phi_reg_1099 <= ap_phi_mux_data_18_V_read57_rewind_phi_fu_644_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_18_V_read57_phi_reg_1099 <= data_18_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_18_V_read57_phi_reg_1099 <= ap_phi_reg_pp0_iter0_data_18_V_read57_phi_reg_1099;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_19_V_read58_phi_reg_1112 <= ap_phi_mux_data_19_V_read58_rewind_phi_fu_658_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_19_V_read58_phi_reg_1112 <= data_19_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_19_V_read58_phi_reg_1112 <= ap_phi_reg_pp0_iter0_data_19_V_read58_phi_reg_1112;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_1_V_read40_phi_reg_878 <= ap_phi_mux_data_1_V_read40_rewind_phi_fu_406_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_1_V_read40_phi_reg_878 <= data_1_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_1_V_read40_phi_reg_878 <= ap_phi_reg_pp0_iter0_data_1_V_read40_phi_reg_878;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_20_V_read59_phi_reg_1125 <= ap_phi_mux_data_20_V_read59_rewind_phi_fu_672_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_20_V_read59_phi_reg_1125 <= data_20_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_20_V_read59_phi_reg_1125 <= ap_phi_reg_pp0_iter0_data_20_V_read59_phi_reg_1125;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_21_V_read60_phi_reg_1138 <= ap_phi_mux_data_21_V_read60_rewind_phi_fu_686_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_21_V_read60_phi_reg_1138 <= data_21_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_21_V_read60_phi_reg_1138 <= ap_phi_reg_pp0_iter0_data_21_V_read60_phi_reg_1138;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_22_V_read61_phi_reg_1151 <= ap_phi_mux_data_22_V_read61_rewind_phi_fu_700_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_22_V_read61_phi_reg_1151 <= data_22_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_22_V_read61_phi_reg_1151 <= ap_phi_reg_pp0_iter0_data_22_V_read61_phi_reg_1151;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_23_V_read62_phi_reg_1164 <= ap_phi_mux_data_23_V_read62_rewind_phi_fu_714_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_23_V_read62_phi_reg_1164 <= data_23_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_23_V_read62_phi_reg_1164 <= ap_phi_reg_pp0_iter0_data_23_V_read62_phi_reg_1164;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_24_V_read63_phi_reg_1177 <= ap_phi_mux_data_24_V_read63_rewind_phi_fu_728_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_24_V_read63_phi_reg_1177 <= data_24_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_24_V_read63_phi_reg_1177 <= ap_phi_reg_pp0_iter0_data_24_V_read63_phi_reg_1177;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_25_V_read64_phi_reg_1190 <= ap_phi_mux_data_25_V_read64_rewind_phi_fu_742_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_25_V_read64_phi_reg_1190 <= data_25_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_25_V_read64_phi_reg_1190 <= ap_phi_reg_pp0_iter0_data_25_V_read64_phi_reg_1190;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_26_V_read65_phi_reg_1203 <= ap_phi_mux_data_26_V_read65_rewind_phi_fu_756_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_26_V_read65_phi_reg_1203 <= data_26_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_26_V_read65_phi_reg_1203 <= ap_phi_reg_pp0_iter0_data_26_V_read65_phi_reg_1203;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_27_V_read66_phi_reg_1216 <= ap_phi_mux_data_27_V_read66_rewind_phi_fu_770_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_27_V_read66_phi_reg_1216 <= data_27_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_27_V_read66_phi_reg_1216 <= ap_phi_reg_pp0_iter0_data_27_V_read66_phi_reg_1216;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_28_V_read67_phi_reg_1229 <= ap_phi_mux_data_28_V_read67_rewind_phi_fu_784_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_28_V_read67_phi_reg_1229 <= data_28_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_28_V_read67_phi_reg_1229 <= ap_phi_reg_pp0_iter0_data_28_V_read67_phi_reg_1229;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_29_V_read68_phi_reg_1242 <= ap_phi_mux_data_29_V_read68_rewind_phi_fu_798_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_29_V_read68_phi_reg_1242 <= data_29_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_29_V_read68_phi_reg_1242 <= ap_phi_reg_pp0_iter0_data_29_V_read68_phi_reg_1242;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_2_V_read41_phi_reg_891 <= ap_phi_mux_data_2_V_read41_rewind_phi_fu_420_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_2_V_read41_phi_reg_891 <= data_2_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_2_V_read41_phi_reg_891 <= ap_phi_reg_pp0_iter0_data_2_V_read41_phi_reg_891;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_30_V_read69_phi_reg_1255 <= ap_phi_mux_data_30_V_read69_rewind_phi_fu_812_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_30_V_read69_phi_reg_1255 <= data_30_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_30_V_read69_phi_reg_1255 <= ap_phi_reg_pp0_iter0_data_30_V_read69_phi_reg_1255;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_31_V_read70_phi_reg_1268 <= ap_phi_mux_data_31_V_read70_rewind_phi_fu_826_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_31_V_read70_phi_reg_1268 <= data_31_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_31_V_read70_phi_reg_1268 <= ap_phi_reg_pp0_iter0_data_31_V_read70_phi_reg_1268;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_3_V_read42_phi_reg_904 <= ap_phi_mux_data_3_V_read42_rewind_phi_fu_434_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_3_V_read42_phi_reg_904 <= data_3_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_3_V_read42_phi_reg_904 <= ap_phi_reg_pp0_iter0_data_3_V_read42_phi_reg_904;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_4_V_read43_phi_reg_917 <= ap_phi_mux_data_4_V_read43_rewind_phi_fu_448_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_4_V_read43_phi_reg_917 <= data_4_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_4_V_read43_phi_reg_917 <= ap_phi_reg_pp0_iter0_data_4_V_read43_phi_reg_917;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_5_V_read44_phi_reg_930 <= ap_phi_mux_data_5_V_read44_rewind_phi_fu_462_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_5_V_read44_phi_reg_930 <= data_5_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_5_V_read44_phi_reg_930 <= ap_phi_reg_pp0_iter0_data_5_V_read44_phi_reg_930;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_6_V_read45_phi_reg_943 <= ap_phi_mux_data_6_V_read45_rewind_phi_fu_476_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_6_V_read45_phi_reg_943 <= data_6_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_6_V_read45_phi_reg_943 <= ap_phi_reg_pp0_iter0_data_6_V_read45_phi_reg_943;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_7_V_read46_phi_reg_956 <= ap_phi_mux_data_7_V_read46_rewind_phi_fu_490_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_7_V_read46_phi_reg_956 <= data_7_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_7_V_read46_phi_reg_956 <= ap_phi_reg_pp0_iter0_data_7_V_read46_phi_reg_956;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_8_V_read47_phi_reg_969 <= ap_phi_mux_data_8_V_read47_rewind_phi_fu_504_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_8_V_read47_phi_reg_969 <= data_8_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_8_V_read47_phi_reg_969 <= ap_phi_reg_pp0_iter0_data_8_V_read47_phi_reg_969;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_41)) begin
        if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd0)) begin
            data_9_V_read48_phi_reg_982 <= ap_phi_mux_data_9_V_read48_rewind_phi_fu_518_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_376_p6 == 1'd1)) begin
            data_9_V_read48_phi_reg_982 <= data_9_V_read;
        end else if ((1'b1 == 1'b1)) begin
            data_9_V_read48_phi_reg_982 <= ap_phi_reg_pp0_iter0_data_9_V_read48_phi_reg_982;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        do_init_reg_372 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_372 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_index_0_i37_reg_850 <= select_ln154_fu_1603_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_index_0_i37_reg_850 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_0_V_write_assign18_reg_1407 <= acc_1_V_1_fu_1616_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_0_V_write_assign18_reg_1407 <= 14'd48;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_1_V_write_assign20_reg_1393 <= acc_1_V_2_fu_1622_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_1_V_write_assign20_reg_1393 <= 14'd16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_2_V_write_assign22_reg_1379 <= acc_3_V_1_fu_1635_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_2_V_write_assign22_reg_1379 <= 14'd16352;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_3_V_write_assign24_reg_1365 <= acc_3_V_2_fu_1641_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_3_V_write_assign24_reg_1365 <= 14'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_4_V_write_assign26_reg_1351 <= acc_5_V_1_fu_1654_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_4_V_write_assign26_reg_1351 <= 14'd16352;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_5_V_write_assign28_reg_1337 <= acc_5_V_2_fu_1660_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_5_V_write_assign28_reg_1337 <= 14'd16;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_6_V_write_assign30_reg_1323 <= acc_7_V_1_fu_1673_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_6_V_write_assign30_reg_1323 <= 14'd16352;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_7_V_write_assign32_reg_1309 <= acc_7_V_2_fu_1679_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_7_V_write_assign32_reg_1309 <= 14'd16368;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_8_V_write_assign34_reg_1295 <= acc_9_V_1_fu_1692_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_8_V_write_assign34_reg_1295 <= 14'd32;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_9_V_write_assign36_reg_1281 <= acc_9_V_2_fu_1698_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_9_V_write_assign36_reg_1281 <= 14'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index38_reg_836 <= w_index_reg_1838;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        w_index38_reg_836 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_0_V_read39_rewind_reg_388 <= data_0_V_read39_phi_reg_865;
        data_10_V_read49_rewind_reg_528 <= data_10_V_read49_phi_reg_995;
        data_11_V_read50_rewind_reg_542 <= data_11_V_read50_phi_reg_1008;
        data_12_V_read51_rewind_reg_556 <= data_12_V_read51_phi_reg_1021;
        data_13_V_read52_rewind_reg_570 <= data_13_V_read52_phi_reg_1034;
        data_14_V_read53_rewind_reg_584 <= data_14_V_read53_phi_reg_1047;
        data_15_V_read54_rewind_reg_598 <= data_15_V_read54_phi_reg_1060;
        data_16_V_read55_rewind_reg_612 <= data_16_V_read55_phi_reg_1073;
        data_17_V_read56_rewind_reg_626 <= data_17_V_read56_phi_reg_1086;
        data_18_V_read57_rewind_reg_640 <= data_18_V_read57_phi_reg_1099;
        data_19_V_read58_rewind_reg_654 <= data_19_V_read58_phi_reg_1112;
        data_1_V_read40_rewind_reg_402 <= data_1_V_read40_phi_reg_878;
        data_20_V_read59_rewind_reg_668 <= data_20_V_read59_phi_reg_1125;
        data_21_V_read60_rewind_reg_682 <= data_21_V_read60_phi_reg_1138;
        data_22_V_read61_rewind_reg_696 <= data_22_V_read61_phi_reg_1151;
        data_23_V_read62_rewind_reg_710 <= data_23_V_read62_phi_reg_1164;
        data_24_V_read63_rewind_reg_724 <= data_24_V_read63_phi_reg_1177;
        data_25_V_read64_rewind_reg_738 <= data_25_V_read64_phi_reg_1190;
        data_26_V_read65_rewind_reg_752 <= data_26_V_read65_phi_reg_1203;
        data_27_V_read66_rewind_reg_766 <= data_27_V_read66_phi_reg_1216;
        data_28_V_read67_rewind_reg_780 <= data_28_V_read67_phi_reg_1229;
        data_29_V_read68_rewind_reg_794 <= data_29_V_read68_phi_reg_1242;
        data_2_V_read41_rewind_reg_416 <= data_2_V_read41_phi_reg_891;
        data_30_V_read69_rewind_reg_808 <= data_30_V_read69_phi_reg_1255;
        data_31_V_read70_rewind_reg_822 <= data_31_V_read70_phi_reg_1268;
        data_3_V_read42_rewind_reg_430 <= data_3_V_read42_phi_reg_904;
        data_4_V_read43_rewind_reg_444 <= data_4_V_read43_phi_reg_917;
        data_5_V_read44_rewind_reg_458 <= data_5_V_read44_phi_reg_930;
        data_6_V_read45_rewind_reg_472 <= data_6_V_read45_phi_reg_943;
        data_7_V_read46_rewind_reg_486 <= data_7_V_read46_phi_reg_956;
        data_8_V_read47_rewind_reg_500 <= data_8_V_read47_phi_reg_969;
        data_9_V_read48_rewind_reg_514 <= data_9_V_read48_phi_reg_982;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln135_reg_1843 <= icmp_ln135_fu_1455_p2;
        icmp_ln135_reg_1843_pp0_iter1_reg <= icmp_ln135_reg_1843;
        icmp_ln154_reg_1833 <= icmp_ln154_fu_1443_p2;
        in_index_reg_1828 <= in_index_fu_1427_p2;
        out_index_reg_1847 <= outidx_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln135_reg_1843_pp0_iter2_reg <= icmp_ln135_reg_1843_pp0_iter1_reg;
        out_index_reg_1847_pp0_iter2_reg <= out_index_reg_1847;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index_reg_1838 <= w_index_fu_1449_p2;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_0_V_read39_rewind_phi_fu_392_p6 = data_0_V_read39_phi_reg_865;
    end else begin
        ap_phi_mux_data_0_V_read39_rewind_phi_fu_392_p6 = data_0_V_read39_rewind_reg_388;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_10_V_read49_rewind_phi_fu_532_p6 = data_10_V_read49_phi_reg_995;
    end else begin
        ap_phi_mux_data_10_V_read49_rewind_phi_fu_532_p6 = data_10_V_read49_rewind_reg_528;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_11_V_read50_rewind_phi_fu_546_p6 = data_11_V_read50_phi_reg_1008;
    end else begin
        ap_phi_mux_data_11_V_read50_rewind_phi_fu_546_p6 = data_11_V_read50_rewind_reg_542;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_12_V_read51_rewind_phi_fu_560_p6 = data_12_V_read51_phi_reg_1021;
    end else begin
        ap_phi_mux_data_12_V_read51_rewind_phi_fu_560_p6 = data_12_V_read51_rewind_reg_556;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_13_V_read52_rewind_phi_fu_574_p6 = data_13_V_read52_phi_reg_1034;
    end else begin
        ap_phi_mux_data_13_V_read52_rewind_phi_fu_574_p6 = data_13_V_read52_rewind_reg_570;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_14_V_read53_rewind_phi_fu_588_p6 = data_14_V_read53_phi_reg_1047;
    end else begin
        ap_phi_mux_data_14_V_read53_rewind_phi_fu_588_p6 = data_14_V_read53_rewind_reg_584;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_15_V_read54_rewind_phi_fu_602_p6 = data_15_V_read54_phi_reg_1060;
    end else begin
        ap_phi_mux_data_15_V_read54_rewind_phi_fu_602_p6 = data_15_V_read54_rewind_reg_598;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_16_V_read55_rewind_phi_fu_616_p6 = data_16_V_read55_phi_reg_1073;
    end else begin
        ap_phi_mux_data_16_V_read55_rewind_phi_fu_616_p6 = data_16_V_read55_rewind_reg_612;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_17_V_read56_rewind_phi_fu_630_p6 = data_17_V_read56_phi_reg_1086;
    end else begin
        ap_phi_mux_data_17_V_read56_rewind_phi_fu_630_p6 = data_17_V_read56_rewind_reg_626;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_18_V_read57_rewind_phi_fu_644_p6 = data_18_V_read57_phi_reg_1099;
    end else begin
        ap_phi_mux_data_18_V_read57_rewind_phi_fu_644_p6 = data_18_V_read57_rewind_reg_640;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_19_V_read58_rewind_phi_fu_658_p6 = data_19_V_read58_phi_reg_1112;
    end else begin
        ap_phi_mux_data_19_V_read58_rewind_phi_fu_658_p6 = data_19_V_read58_rewind_reg_654;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_1_V_read40_rewind_phi_fu_406_p6 = data_1_V_read40_phi_reg_878;
    end else begin
        ap_phi_mux_data_1_V_read40_rewind_phi_fu_406_p6 = data_1_V_read40_rewind_reg_402;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_20_V_read59_rewind_phi_fu_672_p6 = data_20_V_read59_phi_reg_1125;
    end else begin
        ap_phi_mux_data_20_V_read59_rewind_phi_fu_672_p6 = data_20_V_read59_rewind_reg_668;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_21_V_read60_rewind_phi_fu_686_p6 = data_21_V_read60_phi_reg_1138;
    end else begin
        ap_phi_mux_data_21_V_read60_rewind_phi_fu_686_p6 = data_21_V_read60_rewind_reg_682;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_22_V_read61_rewind_phi_fu_700_p6 = data_22_V_read61_phi_reg_1151;
    end else begin
        ap_phi_mux_data_22_V_read61_rewind_phi_fu_700_p6 = data_22_V_read61_rewind_reg_696;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_23_V_read62_rewind_phi_fu_714_p6 = data_23_V_read62_phi_reg_1164;
    end else begin
        ap_phi_mux_data_23_V_read62_rewind_phi_fu_714_p6 = data_23_V_read62_rewind_reg_710;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_24_V_read63_rewind_phi_fu_728_p6 = data_24_V_read63_phi_reg_1177;
    end else begin
        ap_phi_mux_data_24_V_read63_rewind_phi_fu_728_p6 = data_24_V_read63_rewind_reg_724;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_25_V_read64_rewind_phi_fu_742_p6 = data_25_V_read64_phi_reg_1190;
    end else begin
        ap_phi_mux_data_25_V_read64_rewind_phi_fu_742_p6 = data_25_V_read64_rewind_reg_738;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_26_V_read65_rewind_phi_fu_756_p6 = data_26_V_read65_phi_reg_1203;
    end else begin
        ap_phi_mux_data_26_V_read65_rewind_phi_fu_756_p6 = data_26_V_read65_rewind_reg_752;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_27_V_read66_rewind_phi_fu_770_p6 = data_27_V_read66_phi_reg_1216;
    end else begin
        ap_phi_mux_data_27_V_read66_rewind_phi_fu_770_p6 = data_27_V_read66_rewind_reg_766;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_28_V_read67_rewind_phi_fu_784_p6 = data_28_V_read67_phi_reg_1229;
    end else begin
        ap_phi_mux_data_28_V_read67_rewind_phi_fu_784_p6 = data_28_V_read67_rewind_reg_780;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_29_V_read68_rewind_phi_fu_798_p6 = data_29_V_read68_phi_reg_1242;
    end else begin
        ap_phi_mux_data_29_V_read68_rewind_phi_fu_798_p6 = data_29_V_read68_rewind_reg_794;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_2_V_read41_rewind_phi_fu_420_p6 = data_2_V_read41_phi_reg_891;
    end else begin
        ap_phi_mux_data_2_V_read41_rewind_phi_fu_420_p6 = data_2_V_read41_rewind_reg_416;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_30_V_read69_rewind_phi_fu_812_p6 = data_30_V_read69_phi_reg_1255;
    end else begin
        ap_phi_mux_data_30_V_read69_rewind_phi_fu_812_p6 = data_30_V_read69_rewind_reg_808;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_31_V_read70_rewind_phi_fu_826_p6 = data_31_V_read70_phi_reg_1268;
    end else begin
        ap_phi_mux_data_31_V_read70_rewind_phi_fu_826_p6 = data_31_V_read70_rewind_reg_822;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_3_V_read42_rewind_phi_fu_434_p6 = data_3_V_read42_phi_reg_904;
    end else begin
        ap_phi_mux_data_3_V_read42_rewind_phi_fu_434_p6 = data_3_V_read42_rewind_reg_430;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_4_V_read43_rewind_phi_fu_448_p6 = data_4_V_read43_phi_reg_917;
    end else begin
        ap_phi_mux_data_4_V_read43_rewind_phi_fu_448_p6 = data_4_V_read43_rewind_reg_444;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_5_V_read44_rewind_phi_fu_462_p6 = data_5_V_read44_phi_reg_930;
    end else begin
        ap_phi_mux_data_5_V_read44_rewind_phi_fu_462_p6 = data_5_V_read44_rewind_reg_458;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_6_V_read45_rewind_phi_fu_476_p6 = data_6_V_read45_phi_reg_943;
    end else begin
        ap_phi_mux_data_6_V_read45_rewind_phi_fu_476_p6 = data_6_V_read45_rewind_reg_472;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_7_V_read46_rewind_phi_fu_490_p6 = data_7_V_read46_phi_reg_956;
    end else begin
        ap_phi_mux_data_7_V_read46_rewind_phi_fu_490_p6 = data_7_V_read46_rewind_reg_486;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_8_V_read47_rewind_phi_fu_504_p6 = data_8_V_read47_phi_reg_969;
    end else begin
        ap_phi_mux_data_8_V_read47_rewind_phi_fu_504_p6 = data_8_V_read47_rewind_reg_500;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln135_reg_1843 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_data_9_V_read48_rewind_phi_fu_518_p6 = data_9_V_read48_phi_reg_982;
    end else begin
        ap_phi_mux_data_9_V_read48_rewind_phi_fu_518_p6 = data_9_V_read48_rewind_reg_514;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_329)) begin
        if ((icmp_ln135_reg_1843 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_376_p6 = 1'd1;
        end else if ((icmp_ln135_reg_1843 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_376_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_376_p6 = do_init_reg_372;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_376_p6 = do_init_reg_372;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_329)) begin
        if ((icmp_ln135_reg_1843 == 1'd1)) begin
            ap_phi_mux_in_index_0_i37_phi_fu_854_p6 = 32'd0;
        end else if ((icmp_ln135_reg_1843 == 1'd0)) begin
            ap_phi_mux_in_index_0_i37_phi_fu_854_p6 = select_ln154_fu_1603_p3;
        end else begin
            ap_phi_mux_in_index_0_i37_phi_fu_854_p6 = in_index_0_i37_reg_850;
        end
    end else begin
        ap_phi_mux_in_index_0_i37_phi_fu_854_p6 = in_index_0_i37_reg_850;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_329)) begin
        if ((icmp_ln135_reg_1843 == 1'd1)) begin
            ap_phi_mux_w_index38_phi_fu_840_p6 = 6'd0;
        end else if ((icmp_ln135_reg_1843 == 1'd0)) begin
            ap_phi_mux_w_index38_phi_fu_840_p6 = w_index_reg_1838;
        end else begin
            ap_phi_mux_w_index38_phi_fu_840_p6 = w_index38_reg_836;
        end
    end else begin
        ap_phi_mux_w_index38_phi_fu_840_p6 = w_index38_reg_836;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_fu_1455_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_0 = acc_1_V_1_fu_1616_p3;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_1 = acc_1_V_2_fu_1622_p3;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_2 = acc_3_V_1_fu_1635_p3;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_3 = acc_3_V_2_fu_1641_p3;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_4 = acc_5_V_1_fu_1654_p3;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_5 = acc_5_V_2_fu_1660_p3;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_6 = acc_7_V_1_fu_1673_p3;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_7 = acc_7_V_2_fu_1679_p3;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_8 = acc_9_V_1_fu_1692_p3;
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_1843_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_9 = acc_9_V_2_fu_1698_p3;
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1768_ce = 1'b1;
    end else begin
        grp_fu_1768_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1778_ce = 1'b1;
    end else begin
        grp_fu_1778_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1788_ce = 1'b1;
    end else begin
        grp_fu_1788_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1798_ce = 1'b1;
    end else begin
        grp_fu_1798_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_1808_ce = 1'b1;
    end else begin
        grp_fu_1808_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outidx_ce0 = 1'b1;
    end else begin
        outidx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w11_V_ce0 = 1'b1;
    end else begin
        w11_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_V_1_fu_1616_p3 = ((out_index_reg_1847_pp0_iter2_reg[0:0] === 1'b1) ? res_0_V_write_assign18_reg_1407 : grp_fu_1768_p3);

assign acc_1_V_2_fu_1622_p3 = ((out_index_reg_1847_pp0_iter2_reg[0:0] === 1'b1) ? grp_fu_1768_p3 : res_1_V_write_assign20_reg_1393);

assign acc_3_V_1_fu_1635_p3 = ((out_index_reg_1847_pp0_iter2_reg[0:0] === 1'b1) ? res_2_V_write_assign22_reg_1379 : grp_fu_1778_p3);

assign acc_3_V_2_fu_1641_p3 = ((out_index_reg_1847_pp0_iter2_reg[0:0] === 1'b1) ? grp_fu_1778_p3 : res_3_V_write_assign24_reg_1365);

assign acc_5_V_1_fu_1654_p3 = ((out_index_reg_1847_pp0_iter2_reg[0:0] === 1'b1) ? res_4_V_write_assign26_reg_1351 : grp_fu_1788_p3);

assign acc_5_V_2_fu_1660_p3 = ((out_index_reg_1847_pp0_iter2_reg[0:0] === 1'b1) ? grp_fu_1788_p3 : res_5_V_write_assign28_reg_1337);

assign acc_7_V_1_fu_1673_p3 = ((out_index_reg_1847_pp0_iter2_reg[0:0] === 1'b1) ? res_6_V_write_assign30_reg_1323 : grp_fu_1798_p3);

assign acc_7_V_2_fu_1679_p3 = ((out_index_reg_1847_pp0_iter2_reg[0:0] === 1'b1) ? grp_fu_1798_p3 : res_7_V_write_assign32_reg_1309);

assign acc_9_V_1_fu_1692_p3 = ((out_index_reg_1847_pp0_iter2_reg[0:0] === 1'b1) ? res_8_V_write_assign34_reg_1295 : grp_fu_1808_p3);

assign acc_9_V_2_fu_1698_p3 = ((out_index_reg_1847_pp0_iter2_reg[0:0] === 1'b1) ? grp_fu_1808_p3 : res_9_V_write_assign36_reg_1281);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_329 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_41 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_data_0_V_read39_phi_reg_865 = 'bx;

assign ap_phi_reg_pp0_iter0_data_10_V_read49_phi_reg_995 = 'bx;

assign ap_phi_reg_pp0_iter0_data_11_V_read50_phi_reg_1008 = 'bx;

assign ap_phi_reg_pp0_iter0_data_12_V_read51_phi_reg_1021 = 'bx;

assign ap_phi_reg_pp0_iter0_data_13_V_read52_phi_reg_1034 = 'bx;

assign ap_phi_reg_pp0_iter0_data_14_V_read53_phi_reg_1047 = 'bx;

assign ap_phi_reg_pp0_iter0_data_15_V_read54_phi_reg_1060 = 'bx;

assign ap_phi_reg_pp0_iter0_data_16_V_read55_phi_reg_1073 = 'bx;

assign ap_phi_reg_pp0_iter0_data_17_V_read56_phi_reg_1086 = 'bx;

assign ap_phi_reg_pp0_iter0_data_18_V_read57_phi_reg_1099 = 'bx;

assign ap_phi_reg_pp0_iter0_data_19_V_read58_phi_reg_1112 = 'bx;

assign ap_phi_reg_pp0_iter0_data_1_V_read40_phi_reg_878 = 'bx;

assign ap_phi_reg_pp0_iter0_data_20_V_read59_phi_reg_1125 = 'bx;

assign ap_phi_reg_pp0_iter0_data_21_V_read60_phi_reg_1138 = 'bx;

assign ap_phi_reg_pp0_iter0_data_22_V_read61_phi_reg_1151 = 'bx;

assign ap_phi_reg_pp0_iter0_data_23_V_read62_phi_reg_1164 = 'bx;

assign ap_phi_reg_pp0_iter0_data_24_V_read63_phi_reg_1177 = 'bx;

assign ap_phi_reg_pp0_iter0_data_25_V_read64_phi_reg_1190 = 'bx;

assign ap_phi_reg_pp0_iter0_data_26_V_read65_phi_reg_1203 = 'bx;

assign ap_phi_reg_pp0_iter0_data_27_V_read66_phi_reg_1216 = 'bx;

assign ap_phi_reg_pp0_iter0_data_28_V_read67_phi_reg_1229 = 'bx;

assign ap_phi_reg_pp0_iter0_data_29_V_read68_phi_reg_1242 = 'bx;

assign ap_phi_reg_pp0_iter0_data_2_V_read41_phi_reg_891 = 'bx;

assign ap_phi_reg_pp0_iter0_data_30_V_read69_phi_reg_1255 = 'bx;

assign ap_phi_reg_pp0_iter0_data_31_V_read70_phi_reg_1268 = 'bx;

assign ap_phi_reg_pp0_iter0_data_3_V_read42_phi_reg_904 = 'bx;

assign ap_phi_reg_pp0_iter0_data_4_V_read43_phi_reg_917 = 'bx;

assign ap_phi_reg_pp0_iter0_data_5_V_read44_phi_reg_930 = 'bx;

assign ap_phi_reg_pp0_iter0_data_6_V_read45_phi_reg_943 = 'bx;

assign ap_phi_reg_pp0_iter0_data_7_V_read46_phi_reg_956 = 'bx;

assign ap_phi_reg_pp0_iter0_data_8_V_read47_phi_reg_969 = 'bx;

assign ap_phi_reg_pp0_iter0_data_9_V_read48_phi_reg_982 = 'bx;

assign grp_fu_1768_p0 = zext_ln1116_fu_1539_p1;

assign grp_fu_1768_p2 = ((out_index_reg_1847_pp0_iter2_reg[0:0] === 1'b1) ? res_1_V_write_assign20_reg_1393 : res_0_V_write_assign18_reg_1407);

assign grp_fu_1778_p0 = zext_ln1116_fu_1539_p1;

assign grp_fu_1778_p2 = ((out_index_reg_1847_pp0_iter2_reg[0:0] === 1'b1) ? res_3_V_write_assign24_reg_1365 : res_2_V_write_assign22_reg_1379);

assign grp_fu_1788_p0 = zext_ln1116_fu_1539_p1;

assign grp_fu_1788_p2 = ((out_index_reg_1847_pp0_iter2_reg[0:0] === 1'b1) ? res_5_V_write_assign28_reg_1337 : res_4_V_write_assign26_reg_1351);

assign grp_fu_1798_p0 = zext_ln1116_fu_1539_p1;

assign grp_fu_1798_p2 = ((out_index_reg_1847_pp0_iter2_reg[0:0] === 1'b1) ? res_7_V_write_assign32_reg_1309 : res_6_V_write_assign30_reg_1323);

assign grp_fu_1808_p0 = zext_ln1116_fu_1539_p1;

assign grp_fu_1808_p2 = ((out_index_reg_1847_pp0_iter2_reg[0:0] === 1'b1) ? res_9_V_write_assign36_reg_1281 : res_8_V_write_assign34_reg_1295);

assign icmp_ln135_fu_1455_p2 = ((ap_phi_mux_w_index38_phi_fu_840_p6 == 6'd63) ? 1'b1 : 1'b0);

assign icmp_ln154_fu_1443_p2 = (($signed(tmp_430_fu_1433_p4) > $signed(27'd0)) ? 1'b1 : 1'b0);

assign in_index_fu_1427_p2 = (32'd1 + ap_phi_mux_in_index_0_i37_phi_fu_854_p6);

assign outidx_address0 = zext_ln139_fu_1421_p1;

assign select_ln154_fu_1603_p3 = ((icmp_ln154_reg_1833[0:0] === 1'b1) ? 32'd0 : in_index_reg_1828);

assign tmp_430_fu_1433_p4 = {{in_index_fu_1427_p2[31:5]}};

assign tmp_523_fu_1465_p33 = in_index_0_i37_reg_850[4:0];

assign tmp_524_fu_1547_p4 = {{w11_V_q0[7:4]}};

assign tmp_525_fu_1561_p4 = {{w11_V_q0[11:8]}};

assign tmp_526_fu_1575_p4 = {{w11_V_q0[15:12]}};

assign tmp_527_fu_1589_p4 = {{w11_V_q0[19:16]}};

assign trunc_ln145_1_fu_1535_p1 = w11_V_q0[3:0];

assign w11_V_address0 = zext_ln139_fu_1421_p1;

assign w_index_fu_1449_p2 = (6'd1 + ap_phi_mux_w_index38_phi_fu_840_p6);

assign zext_ln1116_fu_1539_p1 = tmp_523_fu_1465_p34;

assign zext_ln139_fu_1421_p1 = ap_phi_mux_w_index38_phi_fu_840_p6;

endmodule //dense_wrapper_ap_ufixed_4_0_4_0_0_ap_fixed_14_7_5_3_0_config11_s
