// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        kernel_data_V_8,
        kernel_data_V_0,
        kernel_data_V_1333,
        kernel_data_V_2334,
        kernel_data_V_3335,
        kernel_data_V_4,
        kernel_data_V_5,
        kernel_data_V_6,
        kernel_data_V_7,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] kernel_data_V_8;
input  [15:0] kernel_data_V_0;
input  [15:0] kernel_data_V_1333;
input  [15:0] kernel_data_V_2334;
input  [15:0] kernel_data_V_3335;
input  [15:0] kernel_data_V_4;
input  [15:0] kernel_data_V_5;
input  [15:0] kernel_data_V_6;
input  [15:0] kernel_data_V_7;
output  [24:0] ap_return_0;
output  [24:0] ap_return_1;
output  [24:0] ap_return_2;
output  [24:0] ap_return_3;
output  [24:0] ap_return_4;
output  [24:0] ap_return_5;
output  [24:0] ap_return_6;
output  [24:0] ap_return_7;
output  [24:0] ap_return_8;
output  [24:0] ap_return_9;
output  [24:0] ap_return_10;
output  [24:0] ap_return_11;
output  [24:0] ap_return_12;
output  [24:0] ap_return_13;
output  [24:0] ap_return_14;
output  [24:0] ap_return_15;
output  [24:0] ap_return_16;
output  [24:0] ap_return_17;
output  [24:0] ap_return_18;
output  [24:0] ap_return_19;
output  [24:0] ap_return_20;
output  [24:0] ap_return_21;
output  [24:0] ap_return_22;
output  [24:0] ap_return_23;
output  [24:0] ap_return_24;
output  [24:0] ap_return_25;
output  [24:0] ap_return_26;
output  [24:0] ap_return_27;
output  [24:0] ap_return_28;
output  [24:0] ap_return_29;
output  [24:0] ap_return_30;
output  [24:0] ap_return_31;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[24:0] ap_return_0;
reg[24:0] ap_return_1;
reg[24:0] ap_return_2;
reg[24:0] ap_return_3;
reg[24:0] ap_return_4;
reg[24:0] ap_return_5;
reg[24:0] ap_return_6;
reg[24:0] ap_return_7;
reg[24:0] ap_return_8;
reg[24:0] ap_return_9;
reg[24:0] ap_return_10;
reg[24:0] ap_return_11;
reg[24:0] ap_return_12;
reg[24:0] ap_return_13;
reg[24:0] ap_return_14;
reg[24:0] ap_return_15;
reg[24:0] ap_return_16;
reg[24:0] ap_return_17;
reg[24:0] ap_return_18;
reg[24:0] ap_return_19;
reg[24:0] ap_return_20;
reg[24:0] ap_return_21;
reg[24:0] ap_return_22;
reg[24:0] ap_return_23;
reg[24:0] ap_return_24;
reg[24:0] ap_return_25;
reg[24:0] ap_return_26;
reg[24:0] ap_return_27;
reg[24:0] ap_return_28;
reg[24:0] ap_return_29;
reg[24:0] ap_return_30;
reg[24:0] ap_return_31;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln135_fu_1809_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_11001;
wire   [6:0] outidx6_address0;
reg    outidx6_ce0;
wire   [2:0] outidx6_q0;
wire   [6:0] w2_V_address0;
reg    w2_V_ce0;
wire   [15:0] w2_V_q0;
reg   [6:0] w_index82_reg_162;
reg   [31:0] in_index_0_i81_reg_176;
reg   [24:0] res_4_V_write_assign80_reg_205;
reg   [24:0] res_3_V_write_assign78_reg_219;
reg   [24:0] res_2_V_write_assign76_reg_233;
reg   [24:0] res_1_V_write_assign74_reg_247;
reg   [24:0] res_0_V_write_assign72_reg_261;
reg   [24:0] res_5_V_write_assign70_reg_275;
reg   [24:0] res_6_V_write_assign68_reg_289;
reg   [24:0] res_7_V_write_assign66_reg_303;
reg   [24:0] res_8_V_write_assign64_reg_317;
reg   [24:0] res_9_V_write_assign62_reg_331;
reg   [24:0] res_10_V_write_assign60_reg_345;
reg   [24:0] res_11_V_write_assign58_reg_359;
reg   [24:0] res_12_V_write_assign56_reg_373;
reg   [24:0] res_13_V_write_assign54_reg_387;
reg   [24:0] res_14_V_write_assign52_reg_401;
reg   [24:0] res_15_V_write_assign50_reg_415;
reg   [24:0] res_16_V_write_assign48_reg_429;
reg   [24:0] res_17_V_write_assign46_reg_443;
reg   [24:0] res_18_V_write_assign44_reg_457;
reg   [24:0] res_19_V_write_assign42_reg_471;
reg   [24:0] res_20_V_write_assign40_reg_485;
reg   [24:0] res_21_V_write_assign38_reg_499;
reg   [24:0] res_22_V_write_assign36_reg_513;
reg   [24:0] res_23_V_write_assign34_reg_527;
reg   [24:0] res_24_V_write_assign32_reg_541;
reg   [24:0] res_25_V_write_assign30_reg_555;
reg   [24:0] res_26_V_write_assign28_reg_569;
reg   [24:0] res_27_V_write_assign26_reg_583;
reg   [24:0] res_28_V_write_assign24_reg_597;
reg   [24:0] res_29_V_write_assign22_reg_611;
reg   [24:0] res_30_V_write_assign20_reg_625;
reg   [24:0] res_31_V_write_assign18_reg_639;
wire   [0:0] icmp_ln19_fu_1655_p2;
reg   [0:0] icmp_ln19_reg_2400;
wire   [0:0] icmp_ln19_1_fu_1661_p2;
reg   [0:0] icmp_ln19_1_reg_2405;
wire   [0:0] or_ln19_2_fu_1739_p2;
reg   [0:0] or_ln19_2_reg_2410;
wire   [0:0] or_ln19_4_fu_1761_p2;
reg   [0:0] or_ln19_4_reg_2415;
wire   [15:0] select_ln19_6_fu_1775_p3;
reg   [15:0] select_ln19_6_reg_2420;
wire   [6:0] w_index_fu_1783_p2;
reg   [6:0] w_index_reg_2430;
wire   [31:0] select_ln154_fu_1801_p3;
reg   [31:0] select_ln154_reg_2435;
reg   [0:0] icmp_ln135_reg_2440;
reg   [0:0] icmp_ln135_reg_2440_pp0_iter1_reg;
reg   [0:0] icmp_ln135_reg_2440_pp0_iter2_reg;
reg   [2:0] out_index_reg_2444;
reg   [2:0] out_index_reg_2444_pp0_iter2_reg;
wire  signed [19:0] sext_ln1116_fu_1844_p1;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg   [6:0] ap_phi_mux_w_index82_phi_fu_166_p6;
wire    ap_block_pp0_stage0;
reg   [31:0] ap_phi_mux_in_index_0_i81_phi_fu_180_p6;
reg   [24:0] ap_phi_mux_acc_V_4_1_i_phi_fu_867_p16;
reg   [24:0] ap_phi_mux_acc_V_3_1_i_phi_fu_837_p16;
reg   [24:0] ap_phi_mux_acc_V_2_1_i_phi_fu_807_p16;
reg   [24:0] ap_phi_mux_acc_V_1_1_i_phi_fu_777_p16;
reg   [24:0] ap_phi_mux_acc_V_0_1_i_phi_fu_747_p16;
reg   [24:0] ap_phi_mux_acc_V_5_1_i_phi_fu_717_p16;
reg   [24:0] ap_phi_mux_acc_V_6_1_i_phi_fu_687_p16;
reg   [24:0] ap_phi_mux_acc_V_7_1_i_phi_fu_657_p16;
reg   [24:0] ap_phi_mux_acc_V_8_1_i_phi_fu_1107_p16;
reg   [24:0] ap_phi_mux_acc_V_9_1_i_phi_fu_1077_p16;
reg   [24:0] ap_phi_mux_acc_V_10_1_i_phi_fu_1047_p16;
reg   [24:0] ap_phi_mux_acc_V_11_1_i_phi_fu_1017_p16;
reg   [24:0] ap_phi_mux_acc_V_12_1_i_phi_fu_987_p16;
reg   [24:0] ap_phi_mux_acc_V_13_1_i_phi_fu_957_p16;
reg   [24:0] ap_phi_mux_acc_V_14_1_i_phi_fu_927_p16;
reg   [24:0] ap_phi_mux_acc_V_15_1_i_phi_fu_897_p16;
reg   [24:0] ap_phi_mux_acc_V_16_1_i_phi_fu_1347_p16;
reg   [24:0] ap_phi_mux_acc_V_17_1_i_phi_fu_1317_p16;
reg   [24:0] ap_phi_mux_acc_V_18_1_i_phi_fu_1287_p16;
reg   [24:0] ap_phi_mux_acc_V_19_1_i_phi_fu_1257_p16;
reg   [24:0] ap_phi_mux_acc_V_20_1_i_phi_fu_1227_p16;
reg   [24:0] ap_phi_mux_acc_V_21_1_i_phi_fu_1197_p16;
reg   [24:0] ap_phi_mux_acc_V_22_1_i_phi_fu_1167_p16;
reg   [24:0] ap_phi_mux_acc_V_23_1_i_phi_fu_1137_p16;
reg   [24:0] ap_phi_mux_acc_V_24_1_i_phi_fu_1587_p16;
reg   [24:0] ap_phi_mux_acc_V_25_1_i_phi_fu_1557_p16;
reg   [24:0] ap_phi_mux_acc_V_26_1_i_phi_fu_1527_p16;
reg   [24:0] ap_phi_mux_acc_V_27_1_i_phi_fu_1497_p16;
reg   [24:0] ap_phi_mux_acc_V_28_1_i_phi_fu_1467_p16;
reg   [24:0] ap_phi_mux_acc_V_29_1_i_phi_fu_1437_p16;
reg   [24:0] ap_phi_mux_acc_V_30_1_i_phi_fu_1407_p16;
reg   [24:0] ap_phi_mux_acc_V_31_1_i_phi_fu_1377_p16;
wire  signed [24:0] grp_fu_2331_p3;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_7_1_i_reg_653;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_6_1_i_reg_683;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_5_1_i_reg_713;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_0_1_i_reg_743;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_1_1_i_reg_773;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_2_1_i_reg_803;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_3_1_i_reg_833;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_4_1_i_reg_863;
wire  signed [24:0] grp_fu_2347_p3;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_15_1_i_reg_893;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_14_1_i_reg_923;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_13_1_i_reg_953;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_12_1_i_reg_983;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_11_1_i_reg_1013;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_10_1_i_reg_1043;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_9_1_i_reg_1073;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_8_1_i_reg_1103;
wire  signed [24:0] grp_fu_2363_p3;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_23_1_i_reg_1133;
wire   [4:0] or_ln_fu_1988_p3;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_22_1_i_reg_1163;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_21_1_i_reg_1193;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_20_1_i_reg_1223;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_19_1_i_reg_1253;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_18_1_i_reg_1283;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_17_1_i_reg_1313;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_16_1_i_reg_1343;
wire  signed [24:0] grp_fu_2379_p3;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_31_1_i_reg_1373;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_30_1_i_reg_1403;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_29_1_i_reg_1433;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_28_1_i_reg_1463;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_27_1_i_reg_1493;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_26_1_i_reg_1523;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_25_1_i_reg_1553;
wire   [24:0] ap_phi_reg_pp0_iter3_acc_V_24_1_i_reg_1583;
wire   [63:0] zext_ln139_fu_1613_p1;
wire   [3:0] trunc_ln145_fu_1619_p1;
wire   [0:0] icmp_ln19_7_fu_1697_p2;
wire   [0:0] icmp_ln19_6_fu_1691_p2;
wire   [0:0] icmp_ln19_5_fu_1685_p2;
wire   [0:0] icmp_ln19_4_fu_1679_p2;
wire   [0:0] icmp_ln19_3_fu_1673_p2;
wire   [0:0] icmp_ln19_2_fu_1667_p2;
wire   [0:0] or_ln19_fu_1711_p2;
wire   [15:0] select_ln19_fu_1703_p3;
wire   [15:0] select_ln19_1_fu_1717_p3;
wire   [0:0] or_ln19_1_fu_1725_p2;
wire   [15:0] select_ln19_2_fu_1731_p3;
wire   [15:0] select_ln19_3_fu_1745_p3;
wire   [15:0] select_ln19_4_fu_1753_p3;
wire   [15:0] select_ln19_5_fu_1767_p3;
wire   [31:0] in_index_fu_1789_p2;
wire   [0:0] icmp_ln154_fu_1795_p2;
wire   [0:0] or_ln19_3_fu_1819_p2;
wire   [0:0] or_ln19_5_fu_1823_p2;
wire   [0:0] or_ln19_6_fu_1828_p2;
wire   [15:0] select_ln19_7_fu_1833_p3;
wire  signed [3:0] trunc_ln145_2_fu_1840_p1;
wire  signed [3:0] tmp_1024_i_fu_1852_p4;
wire  signed [3:0] tmp_1025_i_fu_1866_p4;
wire  signed [3:0] tmp_1026_i_fu_1880_p4;
wire   [4:0] zext_ln1265_fu_1894_p1;
wire   [4:0] phi_ln1265_2_i_fu_1995_p33;
wire  signed [15:0] grp_fu_2331_p0;
wire   [24:0] phi_ln_fu_1897_p10;
wire  signed [15:0] grp_fu_2347_p0;
wire   [24:0] phi_ln1265_1_i_fu_1918_p34;
wire  signed [15:0] grp_fu_2363_p0;
wire   [24:0] phi_ln1265_2_i_fu_1995_p34;
wire  signed [15:0] grp_fu_2379_p0;
wire   [24:0] phi_ln1265_3_i_fu_2065_p34;
reg    grp_fu_2331_ce;
reg    grp_fu_2347_ce;
reg    grp_fu_2363_ce;
reg    grp_fu_2379_ce;
reg   [24:0] ap_return_0_preg;
reg   [24:0] ap_return_1_preg;
reg   [24:0] ap_return_2_preg;
reg   [24:0] ap_return_3_preg;
reg   [24:0] ap_return_4_preg;
reg   [24:0] ap_return_5_preg;
reg   [24:0] ap_return_6_preg;
reg   [24:0] ap_return_7_preg;
reg   [24:0] ap_return_8_preg;
reg   [24:0] ap_return_9_preg;
reg   [24:0] ap_return_10_preg;
reg   [24:0] ap_return_11_preg;
reg   [24:0] ap_return_12_preg;
reg   [24:0] ap_return_13_preg;
reg   [24:0] ap_return_14_preg;
reg   [24:0] ap_return_15_preg;
reg   [24:0] ap_return_16_preg;
reg   [24:0] ap_return_17_preg;
reg   [24:0] ap_return_18_preg;
reg   [24:0] ap_return_19_preg;
reg   [24:0] ap_return_20_preg;
reg   [24:0] ap_return_21_preg;
reg   [24:0] ap_return_22_preg;
reg   [24:0] ap_return_23_preg;
reg   [24:0] ap_return_24_preg;
reg   [24:0] ap_return_25_preg;
reg   [24:0] ap_return_26_preg;
reg   [24:0] ap_return_27_preg;
reg   [24:0] ap_return_28_preg;
reg   [24:0] ap_return_29_preg;
reg   [24:0] ap_return_30_preg;
reg   [24:0] ap_return_31_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_289;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_return_0_preg = 25'd0;
#0 ap_return_1_preg = 25'd0;
#0 ap_return_2_preg = 25'd0;
#0 ap_return_3_preg = 25'd0;
#0 ap_return_4_preg = 25'd0;
#0 ap_return_5_preg = 25'd0;
#0 ap_return_6_preg = 25'd0;
#0 ap_return_7_preg = 25'd0;
#0 ap_return_8_preg = 25'd0;
#0 ap_return_9_preg = 25'd0;
#0 ap_return_10_preg = 25'd0;
#0 ap_return_11_preg = 25'd0;
#0 ap_return_12_preg = 25'd0;
#0 ap_return_13_preg = 25'd0;
#0 ap_return_14_preg = 25'd0;
#0 ap_return_15_preg = 25'd0;
#0 ap_return_16_preg = 25'd0;
#0 ap_return_17_preg = 25'd0;
#0 ap_return_18_preg = 25'd0;
#0 ap_return_19_preg = 25'd0;
#0 ap_return_20_preg = 25'd0;
#0 ap_return_21_preg = 25'd0;
#0 ap_return_22_preg = 25'd0;
#0 ap_return_23_preg = 25'd0;
#0 ap_return_24_preg = 25'd0;
#0 ap_return_25_preg = 25'd0;
#0 ap_return_26_preg = 25'd0;
#0 ap_return_27_preg = 25'd0;
#0 ap_return_28_preg = 25'd0;
#0 ap_return_29_preg = 25'd0;
#0 ap_return_30_preg = 25'd0;
#0 ap_return_31_preg = 25'd0;
end

dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0dEe #(
    .DataWidth( 3 ),
    .AddressRange( 72 ),
    .AddressWidth( 7 ))
outidx6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx6_address0),
    .ce0(outidx6_ce0),
    .q0(outidx6_q0)
);

dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0eOg #(
    .DataWidth( 16 ),
    .AddressRange( 72 ),
    .AddressWidth( 7 ))
w2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_V_address0),
    .ce0(w2_V_ce0),
    .q0(w2_V_q0)
);

myproject_axi_mux_83_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 25 ),
    .din2_WIDTH( 25 ),
    .din3_WIDTH( 25 ),
    .din4_WIDTH( 25 ),
    .din5_WIDTH( 25 ),
    .din6_WIDTH( 25 ),
    .din7_WIDTH( 25 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 25 ))
myproject_axi_mux_83_25_1_1_U17(
    .din0(res_0_V_write_assign72_reg_261),
    .din1(res_1_V_write_assign74_reg_247),
    .din2(res_2_V_write_assign76_reg_233),
    .din3(res_3_V_write_assign78_reg_219),
    .din4(res_4_V_write_assign80_reg_205),
    .din5(res_5_V_write_assign70_reg_275),
    .din6(res_6_V_write_assign68_reg_289),
    .din7(res_7_V_write_assign66_reg_303),
    .din8(out_index_reg_2444_pp0_iter2_reg),
    .dout(phi_ln_fu_1897_p10)
);

myproject_axi_mux_325_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 25 ),
    .din2_WIDTH( 25 ),
    .din3_WIDTH( 25 ),
    .din4_WIDTH( 25 ),
    .din5_WIDTH( 25 ),
    .din6_WIDTH( 25 ),
    .din7_WIDTH( 25 ),
    .din8_WIDTH( 25 ),
    .din9_WIDTH( 25 ),
    .din10_WIDTH( 25 ),
    .din11_WIDTH( 25 ),
    .din12_WIDTH( 25 ),
    .din13_WIDTH( 25 ),
    .din14_WIDTH( 25 ),
    .din15_WIDTH( 25 ),
    .din16_WIDTH( 25 ),
    .din17_WIDTH( 25 ),
    .din18_WIDTH( 25 ),
    .din19_WIDTH( 25 ),
    .din20_WIDTH( 25 ),
    .din21_WIDTH( 25 ),
    .din22_WIDTH( 25 ),
    .din23_WIDTH( 25 ),
    .din24_WIDTH( 25 ),
    .din25_WIDTH( 25 ),
    .din26_WIDTH( 25 ),
    .din27_WIDTH( 25 ),
    .din28_WIDTH( 25 ),
    .din29_WIDTH( 25 ),
    .din30_WIDTH( 25 ),
    .din31_WIDTH( 25 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 25 ))
myproject_axi_mux_325_25_1_1_U18(
    .din0(res_8_V_write_assign64_reg_317),
    .din1(res_9_V_write_assign62_reg_331),
    .din2(res_10_V_write_assign60_reg_345),
    .din3(res_11_V_write_assign58_reg_359),
    .din4(res_12_V_write_assign56_reg_373),
    .din5(res_13_V_write_assign54_reg_387),
    .din6(res_14_V_write_assign52_reg_401),
    .din7(res_15_V_write_assign50_reg_415),
    .din8(res_15_V_write_assign50_reg_415),
    .din9(res_15_V_write_assign50_reg_415),
    .din10(res_15_V_write_assign50_reg_415),
    .din11(res_15_V_write_assign50_reg_415),
    .din12(res_15_V_write_assign50_reg_415),
    .din13(res_15_V_write_assign50_reg_415),
    .din14(res_15_V_write_assign50_reg_415),
    .din15(res_15_V_write_assign50_reg_415),
    .din16(res_15_V_write_assign50_reg_415),
    .din17(res_15_V_write_assign50_reg_415),
    .din18(res_15_V_write_assign50_reg_415),
    .din19(res_15_V_write_assign50_reg_415),
    .din20(res_15_V_write_assign50_reg_415),
    .din21(res_15_V_write_assign50_reg_415),
    .din22(res_15_V_write_assign50_reg_415),
    .din23(res_15_V_write_assign50_reg_415),
    .din24(res_15_V_write_assign50_reg_415),
    .din25(res_15_V_write_assign50_reg_415),
    .din26(res_15_V_write_assign50_reg_415),
    .din27(res_15_V_write_assign50_reg_415),
    .din28(res_15_V_write_assign50_reg_415),
    .din29(res_15_V_write_assign50_reg_415),
    .din30(res_15_V_write_assign50_reg_415),
    .din31(res_15_V_write_assign50_reg_415),
    .din32(zext_ln1265_fu_1894_p1),
    .dout(phi_ln1265_1_i_fu_1918_p34)
);

myproject_axi_mux_325_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 25 ),
    .din2_WIDTH( 25 ),
    .din3_WIDTH( 25 ),
    .din4_WIDTH( 25 ),
    .din5_WIDTH( 25 ),
    .din6_WIDTH( 25 ),
    .din7_WIDTH( 25 ),
    .din8_WIDTH( 25 ),
    .din9_WIDTH( 25 ),
    .din10_WIDTH( 25 ),
    .din11_WIDTH( 25 ),
    .din12_WIDTH( 25 ),
    .din13_WIDTH( 25 ),
    .din14_WIDTH( 25 ),
    .din15_WIDTH( 25 ),
    .din16_WIDTH( 25 ),
    .din17_WIDTH( 25 ),
    .din18_WIDTH( 25 ),
    .din19_WIDTH( 25 ),
    .din20_WIDTH( 25 ),
    .din21_WIDTH( 25 ),
    .din22_WIDTH( 25 ),
    .din23_WIDTH( 25 ),
    .din24_WIDTH( 25 ),
    .din25_WIDTH( 25 ),
    .din26_WIDTH( 25 ),
    .din27_WIDTH( 25 ),
    .din28_WIDTH( 25 ),
    .din29_WIDTH( 25 ),
    .din30_WIDTH( 25 ),
    .din31_WIDTH( 25 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 25 ))
myproject_axi_mux_325_25_1_1_U19(
    .din0(res_23_V_write_assign34_reg_527),
    .din1(res_23_V_write_assign34_reg_527),
    .din2(res_23_V_write_assign34_reg_527),
    .din3(res_23_V_write_assign34_reg_527),
    .din4(res_23_V_write_assign34_reg_527),
    .din5(res_23_V_write_assign34_reg_527),
    .din6(res_23_V_write_assign34_reg_527),
    .din7(res_23_V_write_assign34_reg_527),
    .din8(res_23_V_write_assign34_reg_527),
    .din9(res_23_V_write_assign34_reg_527),
    .din10(res_23_V_write_assign34_reg_527),
    .din11(res_23_V_write_assign34_reg_527),
    .din12(res_23_V_write_assign34_reg_527),
    .din13(res_23_V_write_assign34_reg_527),
    .din14(res_23_V_write_assign34_reg_527),
    .din15(res_23_V_write_assign34_reg_527),
    .din16(res_16_V_write_assign48_reg_429),
    .din17(res_17_V_write_assign46_reg_443),
    .din18(res_18_V_write_assign44_reg_457),
    .din19(res_19_V_write_assign42_reg_471),
    .din20(res_20_V_write_assign40_reg_485),
    .din21(res_21_V_write_assign38_reg_499),
    .din22(res_22_V_write_assign36_reg_513),
    .din23(res_23_V_write_assign34_reg_527),
    .din24(res_23_V_write_assign34_reg_527),
    .din25(res_23_V_write_assign34_reg_527),
    .din26(res_23_V_write_assign34_reg_527),
    .din27(res_23_V_write_assign34_reg_527),
    .din28(res_23_V_write_assign34_reg_527),
    .din29(res_23_V_write_assign34_reg_527),
    .din30(res_23_V_write_assign34_reg_527),
    .din31(res_23_V_write_assign34_reg_527),
    .din32(phi_ln1265_2_i_fu_1995_p33),
    .dout(phi_ln1265_2_i_fu_1995_p34)
);

myproject_axi_mux_325_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 25 ),
    .din2_WIDTH( 25 ),
    .din3_WIDTH( 25 ),
    .din4_WIDTH( 25 ),
    .din5_WIDTH( 25 ),
    .din6_WIDTH( 25 ),
    .din7_WIDTH( 25 ),
    .din8_WIDTH( 25 ),
    .din9_WIDTH( 25 ),
    .din10_WIDTH( 25 ),
    .din11_WIDTH( 25 ),
    .din12_WIDTH( 25 ),
    .din13_WIDTH( 25 ),
    .din14_WIDTH( 25 ),
    .din15_WIDTH( 25 ),
    .din16_WIDTH( 25 ),
    .din17_WIDTH( 25 ),
    .din18_WIDTH( 25 ),
    .din19_WIDTH( 25 ),
    .din20_WIDTH( 25 ),
    .din21_WIDTH( 25 ),
    .din22_WIDTH( 25 ),
    .din23_WIDTH( 25 ),
    .din24_WIDTH( 25 ),
    .din25_WIDTH( 25 ),
    .din26_WIDTH( 25 ),
    .din27_WIDTH( 25 ),
    .din28_WIDTH( 25 ),
    .din29_WIDTH( 25 ),
    .din30_WIDTH( 25 ),
    .din31_WIDTH( 25 ),
    .din32_WIDTH( 5 ),
    .dout_WIDTH( 25 ))
myproject_axi_mux_325_25_1_1_U20(
    .din0(res_24_V_write_assign32_reg_541),
    .din1(res_25_V_write_assign30_reg_555),
    .din2(res_26_V_write_assign28_reg_569),
    .din3(res_27_V_write_assign26_reg_583),
    .din4(res_28_V_write_assign24_reg_597),
    .din5(res_29_V_write_assign22_reg_611),
    .din6(res_30_V_write_assign20_reg_625),
    .din7(res_31_V_write_assign18_reg_639),
    .din8(res_31_V_write_assign18_reg_639),
    .din9(res_31_V_write_assign18_reg_639),
    .din10(res_31_V_write_assign18_reg_639),
    .din11(res_31_V_write_assign18_reg_639),
    .din12(res_31_V_write_assign18_reg_639),
    .din13(res_31_V_write_assign18_reg_639),
    .din14(res_31_V_write_assign18_reg_639),
    .din15(res_31_V_write_assign18_reg_639),
    .din16(res_31_V_write_assign18_reg_639),
    .din17(res_31_V_write_assign18_reg_639),
    .din18(res_31_V_write_assign18_reg_639),
    .din19(res_31_V_write_assign18_reg_639),
    .din20(res_31_V_write_assign18_reg_639),
    .din21(res_31_V_write_assign18_reg_639),
    .din22(res_31_V_write_assign18_reg_639),
    .din23(res_31_V_write_assign18_reg_639),
    .din24(res_31_V_write_assign18_reg_639),
    .din25(res_31_V_write_assign18_reg_639),
    .din26(res_31_V_write_assign18_reg_639),
    .din27(res_31_V_write_assign18_reg_639),
    .din28(res_31_V_write_assign18_reg_639),
    .din29(res_31_V_write_assign18_reg_639),
    .din30(res_31_V_write_assign18_reg_639),
    .din31(res_31_V_write_assign18_reg_639),
    .din32(zext_ln1265_fu_1894_p1),
    .dout(phi_ln1265_3_i_fu_2065_p34)
);

myproject_axi_mac_muladd_16s_4s_25ns_25_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
myproject_axi_mac_muladd_16s_4s_25ns_25_3_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2331_p0),
    .din1(trunc_ln145_2_fu_1840_p1),
    .din2(phi_ln_fu_1897_p10),
    .ce(grp_fu_2331_ce),
    .dout(grp_fu_2331_p3)
);

myproject_axi_mac_muladd_16s_4s_25ns_25_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
myproject_axi_mac_muladd_16s_4s_25ns_25_3_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2347_p0),
    .din1(tmp_1024_i_fu_1852_p4),
    .din2(phi_ln1265_1_i_fu_1918_p34),
    .ce(grp_fu_2347_ce),
    .dout(grp_fu_2347_p3)
);

myproject_axi_mac_muladd_16s_4s_25ns_25_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
myproject_axi_mac_muladd_16s_4s_25ns_25_3_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2363_p0),
    .din1(tmp_1025_i_fu_1866_p4),
    .din2(phi_ln1265_2_i_fu_1995_p34),
    .ce(grp_fu_2363_ce),
    .dout(grp_fu_2363_p3)
);

myproject_axi_mac_muladd_16s_4s_25ns_25_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 25 ),
    .dout_WIDTH( 25 ))
myproject_axi_mac_muladd_16s_4s_25ns_25_3_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_2379_p0),
    .din1(tmp_1026_i_fu_1880_p4),
    .din2(phi_ln1265_3_i_fu_2065_p34),
    .ce(grp_fu_2379_ce),
    .dout(grp_fu_2379_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_0_preg <= ap_phi_mux_acc_V_0_1_i_phi_fu_747_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_10_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_10_preg <= ap_phi_mux_acc_V_10_1_i_phi_fu_1047_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_11_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_11_preg <= ap_phi_mux_acc_V_11_1_i_phi_fu_1017_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_12_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_12_preg <= ap_phi_mux_acc_V_12_1_i_phi_fu_987_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_13_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_13_preg <= ap_phi_mux_acc_V_13_1_i_phi_fu_957_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_14_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_14_preg <= ap_phi_mux_acc_V_14_1_i_phi_fu_927_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_15_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_15_preg <= ap_phi_mux_acc_V_15_1_i_phi_fu_897_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_16_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_16_preg <= ap_phi_mux_acc_V_16_1_i_phi_fu_1347_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_17_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_17_preg <= ap_phi_mux_acc_V_17_1_i_phi_fu_1317_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_18_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_18_preg <= ap_phi_mux_acc_V_18_1_i_phi_fu_1287_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_19_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_19_preg <= ap_phi_mux_acc_V_19_1_i_phi_fu_1257_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_1_preg <= ap_phi_mux_acc_V_1_1_i_phi_fu_777_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_20_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_20_preg <= ap_phi_mux_acc_V_20_1_i_phi_fu_1227_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_21_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_21_preg <= ap_phi_mux_acc_V_21_1_i_phi_fu_1197_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_22_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_22_preg <= ap_phi_mux_acc_V_22_1_i_phi_fu_1167_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_23_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_23_preg <= ap_phi_mux_acc_V_23_1_i_phi_fu_1137_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_24_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_24_preg <= ap_phi_mux_acc_V_24_1_i_phi_fu_1587_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_25_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_25_preg <= ap_phi_mux_acc_V_25_1_i_phi_fu_1557_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_26_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_26_preg <= ap_phi_mux_acc_V_26_1_i_phi_fu_1527_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_27_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_27_preg <= ap_phi_mux_acc_V_27_1_i_phi_fu_1497_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_28_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_28_preg <= ap_phi_mux_acc_V_28_1_i_phi_fu_1467_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_29_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_29_preg <= ap_phi_mux_acc_V_29_1_i_phi_fu_1437_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_2_preg <= ap_phi_mux_acc_V_2_1_i_phi_fu_807_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_30_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_30_preg <= ap_phi_mux_acc_V_30_1_i_phi_fu_1407_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_31_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_31_preg <= ap_phi_mux_acc_V_31_1_i_phi_fu_1377_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_3_preg <= ap_phi_mux_acc_V_3_1_i_phi_fu_837_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_4_preg <= ap_phi_mux_acc_V_4_1_i_phi_fu_867_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_5_preg <= ap_phi_mux_acc_V_5_1_i_phi_fu_717_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_6_preg <= ap_phi_mux_acc_V_6_1_i_phi_fu_687_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_7_preg <= ap_phi_mux_acc_V_7_1_i_phi_fu_657_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_8_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_8_preg <= ap_phi_mux_acc_V_8_1_i_phi_fu_1107_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_9_preg <= 25'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
            ap_return_9_preg <= ap_phi_mux_acc_V_9_1_i_phi_fu_1077_p16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        in_index_0_i81_reg_176 <= select_ln154_reg_2435;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_index_0_i81_reg_176 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_0_V_write_assign72_reg_261 <= ap_phi_mux_acc_V_0_1_i_phi_fu_747_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_0_V_write_assign72_reg_261 <= 25'd33552384;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_10_V_write_assign60_reg_345 <= ap_phi_mux_acc_V_10_1_i_phi_fu_1047_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_10_V_write_assign60_reg_345 <= 25'd33553408;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_11_V_write_assign58_reg_359 <= ap_phi_mux_acc_V_11_1_i_phi_fu_1017_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_11_V_write_assign58_reg_359 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_12_V_write_assign56_reg_373 <= ap_phi_mux_acc_V_12_1_i_phi_fu_987_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_12_V_write_assign56_reg_373 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_13_V_write_assign54_reg_387 <= ap_phi_mux_acc_V_13_1_i_phi_fu_957_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_13_V_write_assign54_reg_387 <= 25'd33552384;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_14_V_write_assign52_reg_401 <= ap_phi_mux_acc_V_14_1_i_phi_fu_927_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_14_V_write_assign52_reg_401 <= 25'd33553408;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_15_V_write_assign50_reg_415 <= ap_phi_mux_acc_V_15_1_i_phi_fu_897_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_15_V_write_assign50_reg_415 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_16_V_write_assign48_reg_429 <= ap_phi_mux_acc_V_16_1_i_phi_fu_1347_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_16_V_write_assign48_reg_429 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_17_V_write_assign46_reg_443 <= ap_phi_mux_acc_V_17_1_i_phi_fu_1317_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_17_V_write_assign46_reg_443 <= 25'd33553408;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_18_V_write_assign44_reg_457 <= ap_phi_mux_acc_V_18_1_i_phi_fu_1287_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_18_V_write_assign44_reg_457 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_19_V_write_assign42_reg_471 <= ap_phi_mux_acc_V_19_1_i_phi_fu_1257_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_19_V_write_assign42_reg_471 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_1_V_write_assign74_reg_247 <= ap_phi_mux_acc_V_1_1_i_phi_fu_777_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_1_V_write_assign74_reg_247 <= 25'd33553408;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_20_V_write_assign40_reg_485 <= ap_phi_mux_acc_V_20_1_i_phi_fu_1227_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_20_V_write_assign40_reg_485 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_21_V_write_assign38_reg_499 <= ap_phi_mux_acc_V_21_1_i_phi_fu_1197_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_21_V_write_assign38_reg_499 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_22_V_write_assign36_reg_513 <= ap_phi_mux_acc_V_22_1_i_phi_fu_1167_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_22_V_write_assign36_reg_513 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_23_V_write_assign34_reg_527 <= ap_phi_mux_acc_V_23_1_i_phi_fu_1137_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_23_V_write_assign34_reg_527 <= 25'd33552384;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_24_V_write_assign32_reg_541 <= ap_phi_mux_acc_V_24_1_i_phi_fu_1587_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_24_V_write_assign32_reg_541 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_25_V_write_assign30_reg_555 <= ap_phi_mux_acc_V_25_1_i_phi_fu_1557_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_25_V_write_assign30_reg_555 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_26_V_write_assign28_reg_569 <= ap_phi_mux_acc_V_26_1_i_phi_fu_1527_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_26_V_write_assign28_reg_569 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_27_V_write_assign26_reg_583 <= ap_phi_mux_acc_V_27_1_i_phi_fu_1497_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_27_V_write_assign26_reg_583 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_28_V_write_assign24_reg_597 <= ap_phi_mux_acc_V_28_1_i_phi_fu_1467_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_28_V_write_assign24_reg_597 <= 25'd33552384;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_29_V_write_assign22_reg_611 <= ap_phi_mux_acc_V_29_1_i_phi_fu_1437_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_29_V_write_assign22_reg_611 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_2_V_write_assign76_reg_233 <= ap_phi_mux_acc_V_2_1_i_phi_fu_807_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_2_V_write_assign76_reg_233 <= 25'd33552384;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_30_V_write_assign20_reg_625 <= ap_phi_mux_acc_V_30_1_i_phi_fu_1407_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_30_V_write_assign20_reg_625 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_31_V_write_assign18_reg_639 <= ap_phi_mux_acc_V_31_1_i_phi_fu_1377_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_31_V_write_assign18_reg_639 <= 25'd33553408;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_3_V_write_assign78_reg_219 <= ap_phi_mux_acc_V_3_1_i_phi_fu_837_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_3_V_write_assign78_reg_219 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_4_V_write_assign80_reg_205 <= ap_phi_mux_acc_V_4_1_i_phi_fu_867_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_4_V_write_assign80_reg_205 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_5_V_write_assign70_reg_275 <= ap_phi_mux_acc_V_5_1_i_phi_fu_717_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_5_V_write_assign70_reg_275 <= 25'd33553408;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_6_V_write_assign68_reg_289 <= ap_phi_mux_acc_V_6_1_i_phi_fu_687_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_6_V_write_assign68_reg_289 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_7_V_write_assign66_reg_303 <= ap_phi_mux_acc_V_7_1_i_phi_fu_657_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_7_V_write_assign66_reg_303 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_8_V_write_assign64_reg_317 <= ap_phi_mux_acc_V_8_1_i_phi_fu_1107_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_8_V_write_assign64_reg_317 <= 25'd33553408;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        res_9_V_write_assign62_reg_331 <= ap_phi_mux_acc_V_9_1_i_phi_fu_1077_p16;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_9_V_write_assign62_reg_331 <= 25'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        w_index82_reg_162 <= w_index_reg_2430;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        w_index82_reg_162 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln135_reg_2440 <= icmp_ln135_fu_1809_p2;
        icmp_ln135_reg_2440_pp0_iter1_reg <= icmp_ln135_reg_2440;
        icmp_ln19_1_reg_2405 <= icmp_ln19_1_fu_1661_p2;
        icmp_ln19_reg_2400 <= icmp_ln19_fu_1655_p2;
        or_ln19_2_reg_2410 <= or_ln19_2_fu_1739_p2;
        or_ln19_4_reg_2415 <= or_ln19_4_fu_1761_p2;
        out_index_reg_2444 <= outidx6_q0;
        select_ln19_6_reg_2420 <= select_ln19_6_fu_1775_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln135_reg_2440_pp0_iter2_reg <= icmp_ln135_reg_2440_pp0_iter1_reg;
        out_index_reg_2444_pp0_iter2_reg <= out_index_reg_2444;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln154_reg_2435 <= select_ln154_fu_1801_p3;
        w_index_reg_2430 <= w_index_fu_1783_p2;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd0)) begin
        ap_phi_mux_acc_V_0_1_i_phi_fu_747_p16 = grp_fu_2331_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_0_1_i_phi_fu_747_p16 = res_0_V_write_assign72_reg_261;
    end else begin
        ap_phi_mux_acc_V_0_1_i_phi_fu_747_p16 = ap_phi_reg_pp0_iter3_acc_V_0_1_i_reg_743;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd2)) begin
        ap_phi_mux_acc_V_10_1_i_phi_fu_1047_p16 = grp_fu_2347_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_10_1_i_phi_fu_1047_p16 = res_10_V_write_assign60_reg_345;
    end else begin
        ap_phi_mux_acc_V_10_1_i_phi_fu_1047_p16 = ap_phi_reg_pp0_iter3_acc_V_10_1_i_reg_1043;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd3)) begin
        ap_phi_mux_acc_V_11_1_i_phi_fu_1017_p16 = grp_fu_2347_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_11_1_i_phi_fu_1017_p16 = res_11_V_write_assign58_reg_359;
    end else begin
        ap_phi_mux_acc_V_11_1_i_phi_fu_1017_p16 = ap_phi_reg_pp0_iter3_acc_V_11_1_i_reg_1013;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd4)) begin
        ap_phi_mux_acc_V_12_1_i_phi_fu_987_p16 = grp_fu_2347_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_12_1_i_phi_fu_987_p16 = res_12_V_write_assign56_reg_373;
    end else begin
        ap_phi_mux_acc_V_12_1_i_phi_fu_987_p16 = ap_phi_reg_pp0_iter3_acc_V_12_1_i_reg_983;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd5)) begin
        ap_phi_mux_acc_V_13_1_i_phi_fu_957_p16 = grp_fu_2347_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_13_1_i_phi_fu_957_p16 = res_13_V_write_assign54_reg_387;
    end else begin
        ap_phi_mux_acc_V_13_1_i_phi_fu_957_p16 = ap_phi_reg_pp0_iter3_acc_V_13_1_i_reg_953;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd6)) begin
        ap_phi_mux_acc_V_14_1_i_phi_fu_927_p16 = grp_fu_2347_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_14_1_i_phi_fu_927_p16 = res_14_V_write_assign52_reg_401;
    end else begin
        ap_phi_mux_acc_V_14_1_i_phi_fu_927_p16 = ap_phi_reg_pp0_iter3_acc_V_14_1_i_reg_923;
    end
end

always @ (*) begin
    if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6))) begin
        ap_phi_mux_acc_V_15_1_i_phi_fu_897_p16 = res_15_V_write_assign50_reg_415;
    end else if ((out_index_reg_2444_pp0_iter2_reg == 3'd7)) begin
        ap_phi_mux_acc_V_15_1_i_phi_fu_897_p16 = grp_fu_2347_p3;
    end else begin
        ap_phi_mux_acc_V_15_1_i_phi_fu_897_p16 = ap_phi_reg_pp0_iter3_acc_V_15_1_i_reg_893;
    end
end

always @ (*) begin
    if ((or_ln_fu_1988_p3 == 5'd16)) begin
        ap_phi_mux_acc_V_16_1_i_phi_fu_1347_p16 = grp_fu_2363_p3;
    end else if (((or_ln_fu_1988_p3 == 5'd22) | (or_ln_fu_1988_p3 == 5'd21) | (or_ln_fu_1988_p3 == 5'd20) | (or_ln_fu_1988_p3 == 5'd19) | (or_ln_fu_1988_p3 == 5'd18) | (or_ln_fu_1988_p3 == 5'd17) | (~(or_ln_fu_1988_p3 == 5'd22) & ~(or_ln_fu_1988_p3 == 5'd21) & ~(or_ln_fu_1988_p3 == 5'd20) & ~(or_ln_fu_1988_p3 == 5'd19) & ~(or_ln_fu_1988_p3 == 5'd18) & ~(or_ln_fu_1988_p3 == 5'd17) & ~(or_ln_fu_1988_p3 == 5'd16)))) begin
        ap_phi_mux_acc_V_16_1_i_phi_fu_1347_p16 = res_16_V_write_assign48_reg_429;
    end else begin
        ap_phi_mux_acc_V_16_1_i_phi_fu_1347_p16 = ap_phi_reg_pp0_iter3_acc_V_16_1_i_reg_1343;
    end
end

always @ (*) begin
    if ((or_ln_fu_1988_p3 == 5'd17)) begin
        ap_phi_mux_acc_V_17_1_i_phi_fu_1317_p16 = grp_fu_2363_p3;
    end else if (((or_ln_fu_1988_p3 == 5'd22) | (or_ln_fu_1988_p3 == 5'd21) | (or_ln_fu_1988_p3 == 5'd20) | (or_ln_fu_1988_p3 == 5'd19) | (or_ln_fu_1988_p3 == 5'd18) | (or_ln_fu_1988_p3 == 5'd16) | (~(or_ln_fu_1988_p3 == 5'd22) & ~(or_ln_fu_1988_p3 == 5'd21) & ~(or_ln_fu_1988_p3 == 5'd20) & ~(or_ln_fu_1988_p3 == 5'd19) & ~(or_ln_fu_1988_p3 == 5'd18) & ~(or_ln_fu_1988_p3 == 5'd17) & ~(or_ln_fu_1988_p3 == 5'd16)))) begin
        ap_phi_mux_acc_V_17_1_i_phi_fu_1317_p16 = res_17_V_write_assign46_reg_443;
    end else begin
        ap_phi_mux_acc_V_17_1_i_phi_fu_1317_p16 = ap_phi_reg_pp0_iter3_acc_V_17_1_i_reg_1313;
    end
end

always @ (*) begin
    if ((or_ln_fu_1988_p3 == 5'd18)) begin
        ap_phi_mux_acc_V_18_1_i_phi_fu_1287_p16 = grp_fu_2363_p3;
    end else if (((or_ln_fu_1988_p3 == 5'd22) | (or_ln_fu_1988_p3 == 5'd21) | (or_ln_fu_1988_p3 == 5'd20) | (or_ln_fu_1988_p3 == 5'd19) | (or_ln_fu_1988_p3 == 5'd17) | (or_ln_fu_1988_p3 == 5'd16) | (~(or_ln_fu_1988_p3 == 5'd22) & ~(or_ln_fu_1988_p3 == 5'd21) & ~(or_ln_fu_1988_p3 == 5'd20) & ~(or_ln_fu_1988_p3 == 5'd19) & ~(or_ln_fu_1988_p3 == 5'd18) & ~(or_ln_fu_1988_p3 == 5'd17) & ~(or_ln_fu_1988_p3 == 5'd16)))) begin
        ap_phi_mux_acc_V_18_1_i_phi_fu_1287_p16 = res_18_V_write_assign44_reg_457;
    end else begin
        ap_phi_mux_acc_V_18_1_i_phi_fu_1287_p16 = ap_phi_reg_pp0_iter3_acc_V_18_1_i_reg_1283;
    end
end

always @ (*) begin
    if ((or_ln_fu_1988_p3 == 5'd19)) begin
        ap_phi_mux_acc_V_19_1_i_phi_fu_1257_p16 = grp_fu_2363_p3;
    end else if (((or_ln_fu_1988_p3 == 5'd22) | (or_ln_fu_1988_p3 == 5'd21) | (or_ln_fu_1988_p3 == 5'd20) | (or_ln_fu_1988_p3 == 5'd18) | (or_ln_fu_1988_p3 == 5'd17) | (or_ln_fu_1988_p3 == 5'd16) | (~(or_ln_fu_1988_p3 == 5'd22) & ~(or_ln_fu_1988_p3 == 5'd21) & ~(or_ln_fu_1988_p3 == 5'd20) & ~(or_ln_fu_1988_p3 == 5'd19) & ~(or_ln_fu_1988_p3 == 5'd18) & ~(or_ln_fu_1988_p3 == 5'd17) & ~(or_ln_fu_1988_p3 == 5'd16)))) begin
        ap_phi_mux_acc_V_19_1_i_phi_fu_1257_p16 = res_19_V_write_assign42_reg_471;
    end else begin
        ap_phi_mux_acc_V_19_1_i_phi_fu_1257_p16 = ap_phi_reg_pp0_iter3_acc_V_19_1_i_reg_1253;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd1)) begin
        ap_phi_mux_acc_V_1_1_i_phi_fu_777_p16 = grp_fu_2331_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_1_1_i_phi_fu_777_p16 = res_1_V_write_assign74_reg_247;
    end else begin
        ap_phi_mux_acc_V_1_1_i_phi_fu_777_p16 = ap_phi_reg_pp0_iter3_acc_V_1_1_i_reg_773;
    end
end

always @ (*) begin
    if ((or_ln_fu_1988_p3 == 5'd20)) begin
        ap_phi_mux_acc_V_20_1_i_phi_fu_1227_p16 = grp_fu_2363_p3;
    end else if (((or_ln_fu_1988_p3 == 5'd22) | (or_ln_fu_1988_p3 == 5'd21) | (or_ln_fu_1988_p3 == 5'd19) | (or_ln_fu_1988_p3 == 5'd18) | (or_ln_fu_1988_p3 == 5'd17) | (or_ln_fu_1988_p3 == 5'd16) | (~(or_ln_fu_1988_p3 == 5'd22) & ~(or_ln_fu_1988_p3 == 5'd21) & ~(or_ln_fu_1988_p3 == 5'd20) & ~(or_ln_fu_1988_p3 == 5'd19) & ~(or_ln_fu_1988_p3 == 5'd18) & ~(or_ln_fu_1988_p3 == 5'd17) & ~(or_ln_fu_1988_p3 == 5'd16)))) begin
        ap_phi_mux_acc_V_20_1_i_phi_fu_1227_p16 = res_20_V_write_assign40_reg_485;
    end else begin
        ap_phi_mux_acc_V_20_1_i_phi_fu_1227_p16 = ap_phi_reg_pp0_iter3_acc_V_20_1_i_reg_1223;
    end
end

always @ (*) begin
    if ((or_ln_fu_1988_p3 == 5'd21)) begin
        ap_phi_mux_acc_V_21_1_i_phi_fu_1197_p16 = grp_fu_2363_p3;
    end else if (((or_ln_fu_1988_p3 == 5'd22) | (or_ln_fu_1988_p3 == 5'd20) | (or_ln_fu_1988_p3 == 5'd19) | (or_ln_fu_1988_p3 == 5'd18) | (or_ln_fu_1988_p3 == 5'd17) | (or_ln_fu_1988_p3 == 5'd16) | (~(or_ln_fu_1988_p3 == 5'd22) & ~(or_ln_fu_1988_p3 == 5'd21) & ~(or_ln_fu_1988_p3 == 5'd20) & ~(or_ln_fu_1988_p3 == 5'd19) & ~(or_ln_fu_1988_p3 == 5'd18) & ~(or_ln_fu_1988_p3 == 5'd17) & ~(or_ln_fu_1988_p3 == 5'd16)))) begin
        ap_phi_mux_acc_V_21_1_i_phi_fu_1197_p16 = res_21_V_write_assign38_reg_499;
    end else begin
        ap_phi_mux_acc_V_21_1_i_phi_fu_1197_p16 = ap_phi_reg_pp0_iter3_acc_V_21_1_i_reg_1193;
    end
end

always @ (*) begin
    if ((or_ln_fu_1988_p3 == 5'd22)) begin
        ap_phi_mux_acc_V_22_1_i_phi_fu_1167_p16 = grp_fu_2363_p3;
    end else if (((or_ln_fu_1988_p3 == 5'd21) | (or_ln_fu_1988_p3 == 5'd20) | (or_ln_fu_1988_p3 == 5'd19) | (or_ln_fu_1988_p3 == 5'd18) | (or_ln_fu_1988_p3 == 5'd17) | (or_ln_fu_1988_p3 == 5'd16) | (~(or_ln_fu_1988_p3 == 5'd22) & ~(or_ln_fu_1988_p3 == 5'd21) & ~(or_ln_fu_1988_p3 == 5'd20) & ~(or_ln_fu_1988_p3 == 5'd19) & ~(or_ln_fu_1988_p3 == 5'd18) & ~(or_ln_fu_1988_p3 == 5'd17) & ~(or_ln_fu_1988_p3 == 5'd16)))) begin
        ap_phi_mux_acc_V_22_1_i_phi_fu_1167_p16 = res_22_V_write_assign36_reg_513;
    end else begin
        ap_phi_mux_acc_V_22_1_i_phi_fu_1167_p16 = ap_phi_reg_pp0_iter3_acc_V_22_1_i_reg_1163;
    end
end

always @ (*) begin
    if (((or_ln_fu_1988_p3 == 5'd22) | (or_ln_fu_1988_p3 == 5'd21) | (or_ln_fu_1988_p3 == 5'd20) | (or_ln_fu_1988_p3 == 5'd19) | (or_ln_fu_1988_p3 == 5'd18) | (or_ln_fu_1988_p3 == 5'd17) | (or_ln_fu_1988_p3 == 5'd16))) begin
        ap_phi_mux_acc_V_23_1_i_phi_fu_1137_p16 = res_23_V_write_assign34_reg_527;
    end else if ((~(or_ln_fu_1988_p3 == 5'd22) & ~(or_ln_fu_1988_p3 == 5'd21) & ~(or_ln_fu_1988_p3 == 5'd20) & ~(or_ln_fu_1988_p3 == 5'd19) & ~(or_ln_fu_1988_p3 == 5'd18) & ~(or_ln_fu_1988_p3 == 5'd17) & ~(or_ln_fu_1988_p3 == 5'd16))) begin
        ap_phi_mux_acc_V_23_1_i_phi_fu_1137_p16 = grp_fu_2363_p3;
    end else begin
        ap_phi_mux_acc_V_23_1_i_phi_fu_1137_p16 = ap_phi_reg_pp0_iter3_acc_V_23_1_i_reg_1133;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd0)) begin
        ap_phi_mux_acc_V_24_1_i_phi_fu_1587_p16 = grp_fu_2379_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_24_1_i_phi_fu_1587_p16 = res_24_V_write_assign32_reg_541;
    end else begin
        ap_phi_mux_acc_V_24_1_i_phi_fu_1587_p16 = ap_phi_reg_pp0_iter3_acc_V_24_1_i_reg_1583;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd1)) begin
        ap_phi_mux_acc_V_25_1_i_phi_fu_1557_p16 = grp_fu_2379_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_25_1_i_phi_fu_1557_p16 = res_25_V_write_assign30_reg_555;
    end else begin
        ap_phi_mux_acc_V_25_1_i_phi_fu_1557_p16 = ap_phi_reg_pp0_iter3_acc_V_25_1_i_reg_1553;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd2)) begin
        ap_phi_mux_acc_V_26_1_i_phi_fu_1527_p16 = grp_fu_2379_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_26_1_i_phi_fu_1527_p16 = res_26_V_write_assign28_reg_569;
    end else begin
        ap_phi_mux_acc_V_26_1_i_phi_fu_1527_p16 = ap_phi_reg_pp0_iter3_acc_V_26_1_i_reg_1523;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd3)) begin
        ap_phi_mux_acc_V_27_1_i_phi_fu_1497_p16 = grp_fu_2379_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_27_1_i_phi_fu_1497_p16 = res_27_V_write_assign26_reg_583;
    end else begin
        ap_phi_mux_acc_V_27_1_i_phi_fu_1497_p16 = ap_phi_reg_pp0_iter3_acc_V_27_1_i_reg_1493;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd4)) begin
        ap_phi_mux_acc_V_28_1_i_phi_fu_1467_p16 = grp_fu_2379_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_28_1_i_phi_fu_1467_p16 = res_28_V_write_assign24_reg_597;
    end else begin
        ap_phi_mux_acc_V_28_1_i_phi_fu_1467_p16 = ap_phi_reg_pp0_iter3_acc_V_28_1_i_reg_1463;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd5)) begin
        ap_phi_mux_acc_V_29_1_i_phi_fu_1437_p16 = grp_fu_2379_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_29_1_i_phi_fu_1437_p16 = res_29_V_write_assign22_reg_611;
    end else begin
        ap_phi_mux_acc_V_29_1_i_phi_fu_1437_p16 = ap_phi_reg_pp0_iter3_acc_V_29_1_i_reg_1433;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd2)) begin
        ap_phi_mux_acc_V_2_1_i_phi_fu_807_p16 = grp_fu_2331_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_2_1_i_phi_fu_807_p16 = res_2_V_write_assign76_reg_233;
    end else begin
        ap_phi_mux_acc_V_2_1_i_phi_fu_807_p16 = ap_phi_reg_pp0_iter3_acc_V_2_1_i_reg_803;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd6)) begin
        ap_phi_mux_acc_V_30_1_i_phi_fu_1407_p16 = grp_fu_2379_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_30_1_i_phi_fu_1407_p16 = res_30_V_write_assign20_reg_625;
    end else begin
        ap_phi_mux_acc_V_30_1_i_phi_fu_1407_p16 = ap_phi_reg_pp0_iter3_acc_V_30_1_i_reg_1403;
    end
end

always @ (*) begin
    if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6))) begin
        ap_phi_mux_acc_V_31_1_i_phi_fu_1377_p16 = res_31_V_write_assign18_reg_639;
    end else if ((out_index_reg_2444_pp0_iter2_reg == 3'd7)) begin
        ap_phi_mux_acc_V_31_1_i_phi_fu_1377_p16 = grp_fu_2379_p3;
    end else begin
        ap_phi_mux_acc_V_31_1_i_phi_fu_1377_p16 = ap_phi_reg_pp0_iter3_acc_V_31_1_i_reg_1373;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd3)) begin
        ap_phi_mux_acc_V_3_1_i_phi_fu_837_p16 = grp_fu_2331_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_3_1_i_phi_fu_837_p16 = res_3_V_write_assign78_reg_219;
    end else begin
        ap_phi_mux_acc_V_3_1_i_phi_fu_837_p16 = ap_phi_reg_pp0_iter3_acc_V_3_1_i_reg_833;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd4)) begin
        ap_phi_mux_acc_V_4_1_i_phi_fu_867_p16 = grp_fu_2331_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_4_1_i_phi_fu_867_p16 = res_4_V_write_assign80_reg_205;
    end else begin
        ap_phi_mux_acc_V_4_1_i_phi_fu_867_p16 = ap_phi_reg_pp0_iter3_acc_V_4_1_i_reg_863;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd5)) begin
        ap_phi_mux_acc_V_5_1_i_phi_fu_717_p16 = grp_fu_2331_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_5_1_i_phi_fu_717_p16 = res_5_V_write_assign70_reg_275;
    end else begin
        ap_phi_mux_acc_V_5_1_i_phi_fu_717_p16 = ap_phi_reg_pp0_iter3_acc_V_5_1_i_reg_713;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd6)) begin
        ap_phi_mux_acc_V_6_1_i_phi_fu_687_p16 = grp_fu_2331_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_6_1_i_phi_fu_687_p16 = res_6_V_write_assign68_reg_289;
    end else begin
        ap_phi_mux_acc_V_6_1_i_phi_fu_687_p16 = ap_phi_reg_pp0_iter3_acc_V_6_1_i_reg_683;
    end
end

always @ (*) begin
    if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6))) begin
        ap_phi_mux_acc_V_7_1_i_phi_fu_657_p16 = res_7_V_write_assign66_reg_303;
    end else if ((out_index_reg_2444_pp0_iter2_reg == 3'd7)) begin
        ap_phi_mux_acc_V_7_1_i_phi_fu_657_p16 = grp_fu_2331_p3;
    end else begin
        ap_phi_mux_acc_V_7_1_i_phi_fu_657_p16 = ap_phi_reg_pp0_iter3_acc_V_7_1_i_reg_653;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd0)) begin
        ap_phi_mux_acc_V_8_1_i_phi_fu_1107_p16 = grp_fu_2347_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd1) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_8_1_i_phi_fu_1107_p16 = res_8_V_write_assign64_reg_317;
    end else begin
        ap_phi_mux_acc_V_8_1_i_phi_fu_1107_p16 = ap_phi_reg_pp0_iter3_acc_V_8_1_i_reg_1103;
    end
end

always @ (*) begin
    if ((out_index_reg_2444_pp0_iter2_reg == 3'd1)) begin
        ap_phi_mux_acc_V_9_1_i_phi_fu_1077_p16 = grp_fu_2347_p3;
    end else if (((out_index_reg_2444_pp0_iter2_reg == 3'd0) | (out_index_reg_2444_pp0_iter2_reg == 3'd2) | (out_index_reg_2444_pp0_iter2_reg == 3'd3) | (out_index_reg_2444_pp0_iter2_reg == 3'd4) | (out_index_reg_2444_pp0_iter2_reg == 3'd5) | (out_index_reg_2444_pp0_iter2_reg == 3'd6) | (out_index_reg_2444_pp0_iter2_reg == 3'd7))) begin
        ap_phi_mux_acc_V_9_1_i_phi_fu_1077_p16 = res_9_V_write_assign62_reg_331;
    end else begin
        ap_phi_mux_acc_V_9_1_i_phi_fu_1077_p16 = ap_phi_reg_pp0_iter3_acc_V_9_1_i_reg_1073;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_289)) begin
        if ((icmp_ln135_reg_2440 == 1'd1)) begin
            ap_phi_mux_in_index_0_i81_phi_fu_180_p6 = 32'd0;
        end else if ((icmp_ln135_reg_2440 == 1'd0)) begin
            ap_phi_mux_in_index_0_i81_phi_fu_180_p6 = select_ln154_reg_2435;
        end else begin
            ap_phi_mux_in_index_0_i81_phi_fu_180_p6 = in_index_0_i81_reg_176;
        end
    end else begin
        ap_phi_mux_in_index_0_i81_phi_fu_180_p6 = in_index_0_i81_reg_176;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_289)) begin
        if ((icmp_ln135_reg_2440 == 1'd1)) begin
            ap_phi_mux_w_index82_phi_fu_166_p6 = 7'd0;
        end else if ((icmp_ln135_reg_2440 == 1'd0)) begin
            ap_phi_mux_w_index82_phi_fu_166_p6 = w_index_reg_2430;
        end else begin
            ap_phi_mux_w_index82_phi_fu_166_p6 = w_index82_reg_162;
        end
    end else begin
        ap_phi_mux_w_index82_phi_fu_166_p6 = w_index82_reg_162;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_fu_1809_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_0 = ap_phi_mux_acc_V_0_1_i_phi_fu_747_p16;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_1 = ap_phi_mux_acc_V_1_1_i_phi_fu_777_p16;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_10 = ap_phi_mux_acc_V_10_1_i_phi_fu_1047_p16;
    end else begin
        ap_return_10 = ap_return_10_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_11 = ap_phi_mux_acc_V_11_1_i_phi_fu_1017_p16;
    end else begin
        ap_return_11 = ap_return_11_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_12 = ap_phi_mux_acc_V_12_1_i_phi_fu_987_p16;
    end else begin
        ap_return_12 = ap_return_12_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_13 = ap_phi_mux_acc_V_13_1_i_phi_fu_957_p16;
    end else begin
        ap_return_13 = ap_return_13_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_14 = ap_phi_mux_acc_V_14_1_i_phi_fu_927_p16;
    end else begin
        ap_return_14 = ap_return_14_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_15 = ap_phi_mux_acc_V_15_1_i_phi_fu_897_p16;
    end else begin
        ap_return_15 = ap_return_15_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_16 = ap_phi_mux_acc_V_16_1_i_phi_fu_1347_p16;
    end else begin
        ap_return_16 = ap_return_16_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_17 = ap_phi_mux_acc_V_17_1_i_phi_fu_1317_p16;
    end else begin
        ap_return_17 = ap_return_17_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_18 = ap_phi_mux_acc_V_18_1_i_phi_fu_1287_p16;
    end else begin
        ap_return_18 = ap_return_18_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_19 = ap_phi_mux_acc_V_19_1_i_phi_fu_1257_p16;
    end else begin
        ap_return_19 = ap_return_19_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_2 = ap_phi_mux_acc_V_2_1_i_phi_fu_807_p16;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_20 = ap_phi_mux_acc_V_20_1_i_phi_fu_1227_p16;
    end else begin
        ap_return_20 = ap_return_20_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_21 = ap_phi_mux_acc_V_21_1_i_phi_fu_1197_p16;
    end else begin
        ap_return_21 = ap_return_21_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_22 = ap_phi_mux_acc_V_22_1_i_phi_fu_1167_p16;
    end else begin
        ap_return_22 = ap_return_22_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_23 = ap_phi_mux_acc_V_23_1_i_phi_fu_1137_p16;
    end else begin
        ap_return_23 = ap_return_23_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_24 = ap_phi_mux_acc_V_24_1_i_phi_fu_1587_p16;
    end else begin
        ap_return_24 = ap_return_24_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_25 = ap_phi_mux_acc_V_25_1_i_phi_fu_1557_p16;
    end else begin
        ap_return_25 = ap_return_25_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_26 = ap_phi_mux_acc_V_26_1_i_phi_fu_1527_p16;
    end else begin
        ap_return_26 = ap_return_26_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_27 = ap_phi_mux_acc_V_27_1_i_phi_fu_1497_p16;
    end else begin
        ap_return_27 = ap_return_27_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_28 = ap_phi_mux_acc_V_28_1_i_phi_fu_1467_p16;
    end else begin
        ap_return_28 = ap_return_28_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_29 = ap_phi_mux_acc_V_29_1_i_phi_fu_1437_p16;
    end else begin
        ap_return_29 = ap_return_29_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_3 = ap_phi_mux_acc_V_3_1_i_phi_fu_837_p16;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_30 = ap_phi_mux_acc_V_30_1_i_phi_fu_1407_p16;
    end else begin
        ap_return_30 = ap_return_30_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_31 = ap_phi_mux_acc_V_31_1_i_phi_fu_1377_p16;
    end else begin
        ap_return_31 = ap_return_31_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_4 = ap_phi_mux_acc_V_4_1_i_phi_fu_867_p16;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_5 = ap_phi_mux_acc_V_5_1_i_phi_fu_717_p16;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_6 = ap_phi_mux_acc_V_6_1_i_phi_fu_687_p16;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_7 = ap_phi_mux_acc_V_7_1_i_phi_fu_657_p16;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_8 = ap_phi_mux_acc_V_8_1_i_phi_fu_1107_p16;
    end else begin
        ap_return_8 = ap_return_8_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln135_reg_2440_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_return_9 = ap_phi_mux_acc_V_9_1_i_phi_fu_1077_p16;
    end else begin
        ap_return_9 = ap_return_9_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2331_ce = 1'b1;
    end else begin
        grp_fu_2331_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2347_ce = 1'b1;
    end else begin
        grp_fu_2347_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2363_ce = 1'b1;
    end else begin
        grp_fu_2363_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_2379_ce = 1'b1;
    end else begin
        grp_fu_2379_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outidx6_ce0 = 1'b1;
    end else begin
        outidx6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w2_V_ce0 = 1'b1;
    end else begin
        w2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_289 = ((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter3_acc_V_0_1_i_reg_743 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_10_1_i_reg_1043 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_11_1_i_reg_1013 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_12_1_i_reg_983 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_13_1_i_reg_953 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_14_1_i_reg_923 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_15_1_i_reg_893 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_16_1_i_reg_1343 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_17_1_i_reg_1313 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_18_1_i_reg_1283 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_19_1_i_reg_1253 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_1_1_i_reg_773 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_20_1_i_reg_1223 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_21_1_i_reg_1193 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_22_1_i_reg_1163 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_23_1_i_reg_1133 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_24_1_i_reg_1583 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_25_1_i_reg_1553 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_26_1_i_reg_1523 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_27_1_i_reg_1493 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_28_1_i_reg_1463 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_29_1_i_reg_1433 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_2_1_i_reg_803 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_30_1_i_reg_1403 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_31_1_i_reg_1373 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_3_1_i_reg_833 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_4_1_i_reg_863 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_5_1_i_reg_713 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_6_1_i_reg_683 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_7_1_i_reg_653 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_8_1_i_reg_1103 = 'bx;

assign ap_phi_reg_pp0_iter3_acc_V_9_1_i_reg_1073 = 'bx;

assign grp_fu_2331_p0 = sext_ln1116_fu_1844_p1;

assign grp_fu_2347_p0 = sext_ln1116_fu_1844_p1;

assign grp_fu_2363_p0 = sext_ln1116_fu_1844_p1;

assign grp_fu_2379_p0 = sext_ln1116_fu_1844_p1;

assign icmp_ln135_fu_1809_p2 = ((ap_phi_mux_w_index82_phi_fu_166_p6 == 7'd71) ? 1'b1 : 1'b0);

assign icmp_ln154_fu_1795_p2 = (($signed(in_index_fu_1789_p2) > $signed(32'd8)) ? 1'b1 : 1'b0);

assign icmp_ln19_1_fu_1661_p2 = ((trunc_ln145_fu_1619_p1 == 4'd1) ? 1'b1 : 1'b0);

assign icmp_ln19_2_fu_1667_p2 = ((trunc_ln145_fu_1619_p1 == 4'd2) ? 1'b1 : 1'b0);

assign icmp_ln19_3_fu_1673_p2 = ((trunc_ln145_fu_1619_p1 == 4'd3) ? 1'b1 : 1'b0);

assign icmp_ln19_4_fu_1679_p2 = ((trunc_ln145_fu_1619_p1 == 4'd4) ? 1'b1 : 1'b0);

assign icmp_ln19_5_fu_1685_p2 = ((trunc_ln145_fu_1619_p1 == 4'd5) ? 1'b1 : 1'b0);

assign icmp_ln19_6_fu_1691_p2 = ((trunc_ln145_fu_1619_p1 == 4'd6) ? 1'b1 : 1'b0);

assign icmp_ln19_7_fu_1697_p2 = ((trunc_ln145_fu_1619_p1 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln19_fu_1655_p2 = ((trunc_ln145_fu_1619_p1 == 4'd0) ? 1'b1 : 1'b0);

assign in_index_fu_1789_p2 = (ap_phi_mux_in_index_0_i81_phi_fu_180_p6 + 32'd1);

assign or_ln19_1_fu_1725_p2 = (icmp_ln19_5_fu_1685_p2 | icmp_ln19_4_fu_1679_p2);

assign or_ln19_2_fu_1739_p2 = (icmp_ln19_3_fu_1673_p2 | icmp_ln19_2_fu_1667_p2);

assign or_ln19_3_fu_1819_p2 = (icmp_ln19_reg_2400 | icmp_ln19_1_reg_2405);

assign or_ln19_4_fu_1761_p2 = (or_ln19_fu_1711_p2 | or_ln19_1_fu_1725_p2);

assign or_ln19_5_fu_1823_p2 = (or_ln19_3_fu_1819_p2 | or_ln19_2_reg_2410);

assign or_ln19_6_fu_1828_p2 = (or_ln19_5_fu_1823_p2 | or_ln19_4_reg_2415);

assign or_ln19_fu_1711_p2 = (icmp_ln19_7_fu_1697_p2 | icmp_ln19_6_fu_1691_p2);

assign or_ln_fu_1988_p3 = {{2'd2}, {out_index_reg_2444_pp0_iter2_reg}};

assign outidx6_address0 = zext_ln139_fu_1613_p1;

assign phi_ln1265_2_i_fu_1995_p33 = {{2'd2}, {out_index_reg_2444_pp0_iter2_reg}};

assign select_ln154_fu_1801_p3 = ((icmp_ln154_fu_1795_p2[0:0] === 1'b1) ? 32'd0 : in_index_fu_1789_p2);

assign select_ln19_1_fu_1717_p3 = ((icmp_ln19_5_fu_1685_p2[0:0] === 1'b1) ? kernel_data_V_5 : kernel_data_V_4);

assign select_ln19_2_fu_1731_p3 = ((icmp_ln19_3_fu_1673_p2[0:0] === 1'b1) ? kernel_data_V_3335 : kernel_data_V_2334);

assign select_ln19_3_fu_1745_p3 = ((icmp_ln19_1_fu_1661_p2[0:0] === 1'b1) ? kernel_data_V_1333 : kernel_data_V_0);

assign select_ln19_4_fu_1753_p3 = ((or_ln19_fu_1711_p2[0:0] === 1'b1) ? select_ln19_fu_1703_p3 : select_ln19_1_fu_1717_p3);

assign select_ln19_5_fu_1767_p3 = ((or_ln19_2_fu_1739_p2[0:0] === 1'b1) ? select_ln19_2_fu_1731_p3 : select_ln19_3_fu_1745_p3);

assign select_ln19_6_fu_1775_p3 = ((or_ln19_4_fu_1761_p2[0:0] === 1'b1) ? select_ln19_4_fu_1753_p3 : select_ln19_5_fu_1767_p3);

assign select_ln19_7_fu_1833_p3 = ((or_ln19_6_fu_1828_p2[0:0] === 1'b1) ? select_ln19_6_reg_2420 : kernel_data_V_8);

assign select_ln19_fu_1703_p3 = ((icmp_ln19_7_fu_1697_p2[0:0] === 1'b1) ? kernel_data_V_7 : kernel_data_V_6);

assign sext_ln1116_fu_1844_p1 = $signed(select_ln19_7_fu_1833_p3);

assign tmp_1024_i_fu_1852_p4 = {{w2_V_q0[7:4]}};

assign tmp_1025_i_fu_1866_p4 = {{w2_V_q0[11:8]}};

assign tmp_1026_i_fu_1880_p4 = {{w2_V_q0[15:12]}};

assign trunc_ln145_2_fu_1840_p1 = w2_V_q0[3:0];

assign trunc_ln145_fu_1619_p1 = ap_phi_mux_in_index_0_i81_phi_fu_180_p6[3:0];

assign w2_V_address0 = zext_ln139_fu_1613_p1;

assign w_index_fu_1783_p2 = (7'd1 + ap_phi_mux_w_index82_phi_fu_166_p6);

assign zext_ln1265_fu_1894_p1 = out_index_reg_2444_pp0_iter2_reg;

assign zext_ln139_fu_1613_p1 = ap_phi_mux_w_index82_phi_fu_166_p6;

endmodule //dense_resource_rf_gt_nin_rem0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s
